const KEY='cutcoach_v2';
const defaults={settings:{age:28,height:179,calories:2300,maintenance:3000,protein:190,fat:65,carbs:200,steps:6000,gymGoal:5,goalWeight:null},days:{},onboarded:false};
let state=load(),selected=today();
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function load(){try{return merge(JSON.parse(localStorage.getItem(KEY)||'{}'))}catch{return structuredClone(defaults)}}
function merge(x){return{...structuredClone(defaults),...x,settings:{...defaults.settings,...(x.settings||{})},days:x.days||{}}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function today(){const d=new Date();return key(d)}
function key(d){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function offset(n){const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()+n);return key(d)}
function day(k=selected){return state.days[k]||(state.days[k]={meals:[],weight:null,steps:0,gym:null,alcohol:null})}
function num(v){const n=Number(String(v??'').replace(',','.'));return Number.isFinite(n)?n:0}
function fmt(v,d=0){return Number(v||0).toLocaleString('de-DE',{minimumFractionDigits:d,maximumFractionDigits:d})}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function totals(k=selected){return(day(k).meals||[]).reduce((a,m)=>({calories:a.calories+num(m.calories),protein:a.protein+num(m.protein),carbs:a.carbs+num(m.carbs),fat:a.fat+num(m.fat)}),{calories:0,protein:0,carbs:0,fat:0})}
function setText(id,v){const e=$(id);if(e)e.textContent=v}
function setBar(id,v,max){const e=$(id);if(e)e.style.width=clamp(v/Math.max(1,max)*100,0,100)+'%'}
function dateLabel(k){const[y,m,d]=k.split('-').map(Number);return new Date(y,m-1,d).toLocaleDateString('de-DE',{weekday:'long',day:'2-digit',month:'long'})}
function lastDays(n=7){return Array.from({length:n},(_,i)=>{const k=offset(i-n+1);return{k,data:state.days[k]||{meals:[],weight:null,steps:0,gym:null,alcohol:null},totals:state.days[k]?totals(k):{calories:0,protein:0,carbs:0,fat:0}}})}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1700)}
function open(id){$('#'+id).classList.add('open')}
function close(el){el.closest('.modal').classList.remove('open')}
function score(){const t=totals(),d=day(),s=state.settings;if(!t.calories&&!d.steps&&d.gym===null&&d.alcohol===null)return null;let v=0;v+=t.calories?Math.max(0,2-Math.abs(t.calories-s.calories)/350):0;v+=clamp(t.protein/s.protein,0,1)*2;v+=clamp(d.steps/s.steps,0,1)*2;v+=d.gym===true?2:d.gym===false?1:0;v+=d.alcohol===false?2:d.alcohol===true?0:0;return Math.round(clamp(v,0,10)*10)/10}
function feedback(){const t=totals(),d=day(),s=state.settings;if(!t.calories)return'Trage deine Mahlzeiten und Aktivität ein. Danach bekommst du eine ehrliche Bewertung.';const x=[];x.push(t.protein>=s.protein-15?'Eiweiß passt':'Eiweiß noch erhöhen');x.push(t.calories>s.calories+250?'Kalorien heute deutlich zu hoch':t.calories<s.calories-500?'Nicht unnötig hungern':'Kalorien liegen gut');x.push(d.steps>=s.steps?'Schrittziel erreicht':fmt(s.steps-d.steps)+' Schritte fehlen');if(d.alcohol===true)x.push('Alkohol als Ausnahme abhaken und normal weitermachen');return x.join(' · ')+'.'}
function render(){const s=state.settings,d=day(),t=totals(),sc=score();setText('#dateLabel',dateLabel(selected));setText('#kcalTotal',fmt(t.calories));setText('#kcalRemain',fmt(Math.max(0,s.calories-t.calories)));setBar('#kcalBar',t.calories,s.calories);setText('#proteinTotal',fmt(t.protein));setText('#carbsTotal',fmt(t.carbs));setText('#fatTotal',fmt(t.fat));setText('#proteinGoal',fmt(s.protein));setText('#carbsGoal',fmt(s.carbs));setText('#fatGoal',fmt(s.fat));setBar('#proteinBar',t.protein,s.protein);setBar('#carbsBar',t.carbs,s.carbs);setBar('#fatBar',t.fat,s.fat);setText('#todayWeight',d.weight?fmt(d.weight,1):'–');setText('#stepGoal',fmt(s.steps));$('#stepsInput').value=d.steps||'';setBar('#stepsBar',d.steps,s.steps);setText('#stepsView',fmt(d.steps));setText('#score',sc===null?'–':fmt(sc,1));setText('#deficit',t.calories?fmt(s.maintenance-t.calories):'–');const wk=lastDays();setText('#gymWeek',wk.filter(x=>x.data.gym===true).length);setText('#feedback',feedback());setText('#foodKcal',fmt(t.calories));setText('#foodProtein',fmt(t.protein));setText('#foodOpen',fmt(Math.max(0,s.calories-t.calories)));$$('[data-gym],[data-alcohol]').forEach(b=>b.classList.remove('on'));if(d.gym!==null)$(`[data-gym="${d.gym}"]`).classList.add('on');if(d.alcohol!==null)$(`[data-alcohol="${d.alcohol}"]`).classList.add('on');renderMeals();renderProgress();fillSettings();save()}
function renderMeals(){const wrap=$('#mealList'),groups=['Frühstück','Mittagessen','Abendessen','Snack'].map(type=>({type,items:(day().meals||[]).filter(m=>m.type===type)})).filter(g=>g.items.length),icons={'Frühstück':'☀️','Mittagessen':'🥗','Abendessen':'🌙','Snack':'🍎'};if(!groups.length){wrap.innerHTML='<article class="card empty">Noch keine Mahlzeiten. Tippe auf „+ Mahlzeit“.</article>';return}wrap.innerHTML=groups.map(g=>`<section class="meal-group"><h3>${g.type}</h3><article class="card">${g.items.map(m=>`<div class="meal"><div class="meal-icon">${icons[g.type]}</div><div class="meal-main"><b>${esc(m.name)}</b><small>E ${fmt(m.protein)} · KH ${fmt(m.carbs)} · F ${fmt(m.fat)} g</small></div><div class="meal-kcal">${fmt(m.calories)}<small>kcal</small></div><button class="meal-delete" data-delete-meal="${m.id}">×</button></div>`).join('')}</article></section>`).join('');$$('[data-delete-meal]').forEach(b=>b.onclick=()=>{day().meals=day().meals.filter(m=>String(m.id)!==b.dataset.deleteMeal);render()})}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function renderProgress(){const ds=lastDays(),s=state.settings,valid=ds.filter(x=>x.totals.calories>0);$('#weekBars').innerHTML=ds.map(x=>{const d=new Date(x.k+'T12:00:00'),h=clamp(x.totals.calories/Math.max(1,s.calories)*125,6,140);return`<div class="week-item"><i style="height:${h}px;opacity:${x.totals.calories?1:.18}"></i>${d.toLocaleDateString('de-DE',{weekday:'short'}).slice(0,2)}</div>`}).join('');const weights=Object.entries(state.days).filter(([,v])=>v.weight).sort((a,b)=>a[0].localeCompare(b[0]));let trend=null;if(weights.length>1)trend=weights.at(-1)[1].weight-weights[Math.max(0,weights.length-8)][1].weight;setText('#weightTrend',trend===null?'–':(trend>0?'+':'')+fmt(trend,1));setText('#avgProtein',fmt(valid.length?valid.reduce((a,x)=>a+x.totals.protein,0)/valid.length:0));setText('#weekGym',ds.filter(x=>x.data.gym===true).length);setText('#avgSteps',fmt(ds.reduce((a,x)=>a+(x.data.steps||0),0)/7));$('#weightHistory').innerHTML=weights.length?weights.slice(-12).reverse().map(([k,v])=>`<div class="weight-row"><span>${new Date(k+'T12:00:00').toLocaleDateString('de-DE')}</span><b>${fmt(v.weight,1)} kg</b></div>`).join(''):'<div class="empty">Noch keine Gewichtseinträge.</div>';let advice='Nach mindestens sieben Tagen wird die Bewertung aussagekräftiger.';if(valid.length>=5&&weights.length>=2){advice=trend<-1.2?'Du verlierst sehr schnell. Erhöhe die Kalorien leicht und achte auf Leistung, Schlaf und Eiweiß.':trend<-0.3?'Der Trend passt. Behalte Kalorien, Eiweiß und Training zunächst unverändert bei.':trend>0.2?'Das Gewicht steigt. Prüfe die Einträge. Hält das zwei Wochen an, reduziere um etwa 100–150 kcal.':'Der Trend ist fast stabil. Noch eine Woche sauber dokumentieren, bevor du etwas änderst.'}setText('#weekAdvice',advice)}
function fillSettings(){const map={setAge:'age',setHeight:'height',setCalories:'calories',setMaintenance:'maintenance',setProtein:'protein',setFat:'fat',setCarbs:'carbs',setSteps:'steps',setGymGoal:'gymGoal',setGoalWeight:'goalWeight'};Object.entries(map).forEach(([id,k])=>{const e=$('#'+id);if(document.activeElement!==e)e.value=state.settings[k]??''})}
$$('[data-tab]').forEach(b=>b.onclick=()=>{$$('[data-tab]').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.screen').forEach(x=>x.classList.remove('active'));$(`[data-screen="${b.dataset.tab}"]`).classList.add('active');scrollTo({top:0,behavior:'smooth'})});
$$('[data-open]').forEach(b=>b.onclick=()=>{if(b.dataset.open==='weightModal')$('#weightInput').value=day().weight||'';open(b.dataset.open)});$$('[data-close]').forEach(b=>b.onclick=()=>close(b));$$('.modal').forEach(m=>m.onclick=e=>{if(e.target===m&&m.id!=='onboardingModal')m.classList.remove('open')});
$('#saveMeal').onclick=()=>{const name=$('#mealName').value.trim(),calories=num($('#mealCalories').value);if(!name||calories<=0)return toast('Name und Kalorien eintragen');day().meals.push({id:Date.now(),name,type:$('#mealType').value,calories,protein:num($('#mealProtein').value),carbs:num($('#mealCarbs').value),fat:num($('#mealFat').value)});['mealName','mealCalories','mealProtein','mealCarbs','mealFat'].forEach(id=>$('#'+id).value='');$('#mealModal').classList.remove('open');render();toast('Mahlzeit gespeichert')};
$('#saveWeight').onclick=()=>{const w=num($('#weightInput').value);if(w<30||w>300)return toast('Gültiges Gewicht eintragen');day().weight=Math.round(w*10)/10;$('#weightModal').classList.remove('open');render();toast('Gewicht gespeichert')};
$('#saveSteps').onclick=()=>{day().steps=Math.max(0,Math.round(num($('#stepsInput').value)));render();toast('Schritte gespeichert')};
$$('[data-gym]').forEach(b=>b.onclick=()=>{day().gym=b.dataset.gym==='true';render()});$$('[data-alcohol]').forEach(b=>b.onclick=()=>{day().alcohol=b.dataset.alcohol==='true';render()});
$('#saveSettings').onclick=()=>{const map={setAge:'age',setHeight:'height',setCalories:'calories',setMaintenance:'maintenance',setProtein:'protein',setFat:'fat',setCarbs:'carbs',setSteps:'steps',setGymGoal:'gymGoal',setGoalWeight:'goalWeight'};Object.entries(map).forEach(([id,k])=>{const v=num($('#'+id).value);state.settings[k]=v||defaults.settings[k]});render();toast('Einstellungen gespeichert')};
$('#startApp').onclick=()=>{const w=num($('#startWeight').value);if(w<30||w>300)return toast('Startgewicht eintragen');day(today()).weight=Math.round(w*10)/10;const g=num($('#startGoal').value);if(g)state.settings.goalWeight=g;state.onboarded=true;$('#onboardingModal').classList.remove('open');render();toast('CutCoach gestartet')};
$('#exportData').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='CutCoach-Backup-'+today()+'.json';a.click();URL.revokeObjectURL(a.href)};
$('#importData').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{state=merge(JSON.parse(r.result));render();toast('Backup importiert')}catch{toast('Ungültiges Backup')}};r.readAsText(f);e.target.value=''};
$('#resetData').onclick=()=>{if(confirm('Wirklich alle Daten löschen?')){localStorage.removeItem(KEY);state=structuredClone(defaults);selected=today();render();open('onboardingModal')}};
$('#installInfo').onclick=()=>alert('Auf dem iPhone in Safari: unten auf Teilen tippen → Zum Home-Bildschirm → Hinzufügen. Danach CutCoach immer über das neue Symbol öffnen.');
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
render();if(!state.onboarded)setTimeout(()=>open('onboardingModal'),150);