'use strict';
(function(){
  const VERSION='4.6.0';
  const META_KEY='cutcoach_health_sync_v1';
  const MAX_STEPS=100000;
  const SHORTCUT_INSTALL_URL='';
  const SYNC_BASE='https://reemaru1.github.io/cutcoach/#health-sync?steps=';
  const baseRender=window.render;

  function readMeta(){try{const value=JSON.parse(localStorage.getItem(META_KEY)||'{}');return value&&typeof value==='object'&&!Array.isArray(value)?value:{}}catch{return {}}}
  function writeMeta(value){try{localStorage.setItem(META_KEY,JSON.stringify(value));return true}catch{return false}}
  function standalone(){return Boolean(window.matchMedia?.('(display-mode: standalone)').matches||navigator.standalone)}
  function sourceLabel(source){return source==='fitness'?'Apple Fitness':'Apple Health'}
  function formatStamp(value){const date=new Date(value);if(!Number.isFinite(date.getTime()))return 'unbekannt';return date.toDateString()===new Date().toDateString()?`heute ${date.toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'})}`:date.toLocaleString('de-DE',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}
  function parseStepNumber(value){let text=String(value??'').trim().replace(/[\s\u00a0\u202f]/g,'');if(!text)return null;text=text.replace(/([,.])0+$/,'');if(/^\d{1,3}([.,]\d{3})+$/.test(text))text=text.replace(/[.,]/g,'');if(!/^\d{1,6}$/.test(text))return null;const number=Math.round(Number(text));return Number.isFinite(number)&&number>=0&&number<=MAX_STEPS?number:null}
  function cleanHash(){try{history.replaceState(null,'',`${location.pathname}${location.search}#today`)}catch{location.hash='today'}}
  function parseIncoming(){const raw=location.hash.replace(/^#/,'');let query='';if(raw.startsWith('health-sync?'))query=raw.slice(12);else if(raw.startsWith('health-sync&'))query=raw.slice(12);else if(raw.startsWith('syncSteps='))query=raw.replace(/^syncSteps=/,'steps=');else return null;const params=new URLSearchParams(query),steps=parseStepNumber(params.get('steps'));if(steps===null)return{error:'Die übergebene Schrittzahl ist ungültig.'};const date=String(params.get('date')||todayKey());if(!validDateKey(date)||date>todayKey())return{error:'Das übergebene Datum ist ungültig.'};return{steps,date,source:/^(fitness)$/i.test(params.get('source')||'')?'fitness':'health'}}
  function rememberSync(payload,previous){const meta=readMeta(),syncedAt=new Date().toISOString();meta.version=1;meta.connected=true;meta.last={date:payload.date,steps:payload.steps,previous,syncedAt,source:payload.source,context:standalone()?'standalone':'browser'};meta.days=meta.days&&typeof meta.days==='object'&&!Array.isArray(meta.days)?meta.days:{};meta.days[payload.date]={steps:payload.steps,previous,syncedAt,source:payload.source,context:meta.last.context};const keys=Object.keys(meta.days).sort();while(keys.length>120)delete meta.days[keys.shift()];writeMeta(meta)}
  function applySync(payload){const data=day(payload.date,true),previous=data.steps;data.steps=payload.steps;if(!saveState(true)){data.steps=previous;pruneDay(payload.date);toast('Health-Sync konnte nicht gespeichert werden.');return false}rememberSync(payload,previous);selectedDate=payload.date;cleanHash();document.querySelector('[data-tab="today"]')?.click();window.render();toast(`${sourceLabel(payload.source)}: ${fmt(payload.steps)} Schritte übernommen`);return true}
  function processIncoming(){const payload=parseIncoming();if(!payload)return false;if(payload.error){cleanHash();toast(payload.error);return true}return applySync(payload)}
  function copyText(text){if(navigator.clipboard?.writeText)return navigator.clipboard.writeText(text);const area=document.createElement('textarea');area.value=text;area.style.position='fixed';area.style.opacity='0';document.body.append(area);area.select();document.execCommand('copy');area.remove();return Promise.resolve()}
  function openShortcuts(){if(SHORTCUT_INSTALL_URL){location.href=SHORTCUT_INSTALL_URL;return}location.href='shortcuts://';setTimeout(()=>toast('Kurzbefehle wurde geöffnet. Der fertige Ein-Klick-Link wird nach deinem Test hinterlegt.'),400)}
  function setWizardStep(step){document.querySelectorAll('[data-health-step]').forEach(item=>item.hidden=item.dataset.healthStep!==String(step))}
  function ensureUi(){
    const steps=document.querySelector('.steps-card');
    if(steps&&!document.querySelector('#healthSyncPanel'))steps.querySelector('.bar')?.insertAdjacentHTML('afterend','<div class="health-sync-panel" id="healthSyncPanel" data-state="ready"><div class="health-sync-status" aria-live="polite"><span class="health-sync-heart" aria-hidden="true">♥</span><div><strong id="healthSyncTitle">Apple Health verbinden</strong><small id="healthSyncText">Einmal einrichten, danach Schritte übernehmen</small></div></div><button type="button" class="secondary health-sync-open" id="healthSyncOpen">Verbinden</button></div>');
    if(!document.querySelector('#healthSyncModal')){
      document.body.insertAdjacentHTML('beforeend','<div class="modal" id="healthSyncModal" role="dialog" aria-modal="true" aria-hidden="true" aria-labelledby="healthSyncModalTitle"><div class="sheet health-sync-sheet simple-health-sheet"><div class="sheet-head"><div><h2 id="healthSyncModalTitle">Apple Health verbinden</h2><small>Kostenlos · dauert nur einmal</small></div><button type="button" id="healthSyncClose" aria-label="Schließen">×</button></div><section data-health-step="1"><div class="health-hero"><span>♥</span><h3>Schritte automatisch übernehmen</h3><p>CutCoach nutzt dafür einen kostenlosen Apple-Kurzbefehl. Deine Gesundheitsdaten bleiben auf deinem iPhone.</p></div><button type="button" class="health-primary" id="healthInstall"> Kurzbefehl installieren</button><button type="button" class="secondary health-secondary" id="healthTestOpen">Erst einmal testen</button><small class="health-honest">Apple verlangt beim ersten Mal eine Bestätigung für den Health-Zugriff.</small></section><section data-health-step="2" hidden><div class="health-hero compact"><span>✓</span><h3>Verbindung testen</h3><p>Trage irgendeinen Testwert ein. Danach siehst du sofort, ob die Übertragung funktioniert.</p></div><label class="health-test-label">Test-Schritte<input id="healthSyncTestInput" type="number" min="0" max="100000" inputmode="numeric" placeholder="z. B. 4500"></label><button type="button" class="health-primary" id="healthSyncTest">Testwert übernehmen</button><button type="button" class="secondary health-secondary" id="healthBack">Zurück</button></section><section data-health-step="3" hidden><div class="health-success"><span>✓</span><h3>CutCoach ist bereit</h3><p>Der Testwert wurde übernommen. Sobald der freigegebene Kurzbefehl-Link hinterlegt ist, installieren Freunde ihn mit einem Tipp.</p></div><button type="button" class="health-primary" id="healthDone">Fertig</button></section></div></div>');
      const modal=document.querySelector('#healthSyncModal'),close=()=>closeModal(modal);document.querySelector('#healthSyncClose').onclick=close;modal.onclick=e=>{if(e.target===modal)close()};document.querySelector('#healthInstall').onclick=openShortcuts;document.querySelector('#healthTestOpen').onclick=()=>setWizardStep(2);document.querySelector('#healthBack').onclick=()=>setWizardStep(1);document.querySelector('#healthDone').onclick=close;document.querySelector('#healthSyncTest').onclick=()=>{const input=document.querySelector('#healthSyncTestInput'),value=parseStepNumber(input.value);if(value===null){toast('Bitte eine gültige Schrittzahl eingeben.');return}if(applySync({steps:value,date:todayKey(),source:'health'}))setWizardStep(3)};
    }
    const open=document.querySelector('#healthSyncOpen');if(open&&!open.dataset.bound){open.dataset.bound='1';open.onclick=()=>{setWizardStep(readMeta().connected?2:1);openModal('healthSyncModal')}}
  }
  function renderStatus(){const panel=document.querySelector('#healthSyncPanel'),title=document.querySelector('#healthSyncTitle'),text=document.querySelector('#healthSyncText'),open=document.querySelector('#healthSyncOpen');if(!panel||!title||!text)return;const meta=readMeta(),entry=meta.days?.[selectedDate],current=day(selectedDate,false).steps;if(entry){const same=current===entry.steps;panel.dataset.state=same?'synced':'changed';title.textContent=same?'Apple Health verbunden':'Seit dem Sync manuell geändert';text.textContent=same?`${formatStamp(entry.syncedAt)} · ${fmt(entry.steps)} Schritte`:`Health: ${fmt(entry.steps)} · aktuell: ${current===null?'–':fmt(current)}`;if(open)open.textContent='Verwalten'}else if(meta.connected){panel.dataset.state='ready';title.textContent='Apple Health verbunden';text.textContent=meta.last?`Letzter Sync ${formatStamp(meta.last.syncedAt)}`:'Bereit für die erste Synchronisierung';if(open)open.textContent='Verwalten'}else{panel.dataset.state='ready';title.textContent='Apple Health verbinden';text.textContent='Einmal einrichten, danach Schritte übernehmen';if(open)open.textContent='Verbinden'}}
  function postRender(){ensureUi();renderStatus();const version=document.querySelector('#appVersion');if(version)version.textContent=`Version ${VERSION}`}
  window.CutCoachHealthSync={version:VERSION,process:processIncoming,baseUrl:SYNC_BASE};window.render=function(){baseRender();postRender()};window.addEventListener('hashchange',processIncoming);window.addEventListener('pageshow',()=>{processIncoming();postRender()});document.addEventListener('visibilitychange',()=>{if(!document.hidden)processIncoming()});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{window.render();setTimeout(processIncoming,40)},{once:true});else{window.render();setTimeout(processIncoming,40)}
})();