'use strict';
(function(){
  const VERSION='4.9.0';
  const SETUP='cutcoach_health_setup_v1',LINK='cutcoach_health_shortcut_link_v1',SYNC='cutcoach_health_sync_v1';
  const PREFIX='https://reemaru1.github.io/cutcoach/#health-sync?steps=';
  const baseRender=window.render;
  const read=(key)=>{try{const v=JSON.parse(localStorage.getItem(key)||'{}');return v&&typeof v==='object'?v:{}}catch{return {}}};
  const linked=()=>Boolean(localStorage.getItem(LINK));
  const connected=()=>Boolean(read(SYNC).last);
  const close=id=>closeModal(document.querySelector('#'+id));
  const copy=async text=>{try{await navigator.clipboard.writeText(text);toast('Kopiert.')}catch{toast('Kopieren nicht möglich.')}};
  function saveLink(value){const v=String(value||'').trim();if(!/^https:\/\/(www\.)?icloud\.com\/shortcuts\/[A-Za-z0-9]+(?:\?.*)?$/.test(v))return false;localStorage.setItem(LINK,v);return true}
  function ensureCard(){const old=document.querySelector('#healthSyncPanel');if(!old||document.querySelector('#healthPremiumCard'))return;old.id='healthPremiumCard';old.className='health-premium-card';old.innerHTML='<div class="health-premium-head"><span class="health-premium-icon">♥</span><div><small>Apple Health</small><strong id="healthPremiumTitle"></strong></div><span class="health-status-dot"></span></div><p id="healthPremiumText"></p><div class="health-premium-meta" id="healthPremiumMeta" hidden><span id="healthPremiumSteps"></span><small id="healthPremiumTime"></small></div><button type="button" id="healthPremiumAction"></button>';document.querySelector('#healthPremiumAction').onclick=()=>openModal(linked()?'healthInstallModal':'healthBuildModal')}
  function ensureBuild(){if(document.querySelector('#healthBuildModal'))return;document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="healthBuildModal" role="dialog" aria-modal="true"><div class="sheet health-owner-sheet"><div class="sheet-head"><div><h2>CutCoach Sync erstellen</h2><small>Einmalig auf deinem iPhone</small></div><button id="healthBuildClose">×</button></div><div class="health-owner-alert danger"><strong>Der vorhandene lila Kurzbefehl ist falsch.</strong><p>Er erstellt nur Freigabelinks und liest keine Health-Daten.</p></div><div class="health-build-actions"><div><b>1</b><span>In Kurzbefehle oben rechts auf <strong>+</strong> tippen und den Namen <strong>CutCoach Sync</strong> vergeben.</span></div><div><b>2</b><span>Aktion <strong>Gesundheitsdaten suchen</strong>: Typ <strong>Schritte</strong>, Datum <strong>ist heute</strong>.</span></div><div><b>3</b><span>Aktion <strong>Statistik berechnen</strong>: <strong>Summe</strong>.</span></div><div><b>4</b><span>Aktion <strong>Text</strong>: Basisadresse einfügen und direkt dahinter die Variable <strong>Summe</strong> setzen.</span></div><div><b>5</b><span>Aktion <strong>URLs öffnen</strong> hinzufügen und den Kurzbefehl starten.</span></div></div><button id="healthCopyPrefix">Basisadresse kopieren</button><code class="health-prefix">${PREFIX}</code><button class="secondary" id="healthOpenBuild">Neuen Kurzbefehl erstellen</button><div class="health-interface-test"><strong>Zuerst CutCoach testen</strong><p>Dieser Test prüft nur die Übergabe an CutCoach – ganz ohne Health.</p><button id="healthLocalTest">Test mit 4.321 Schritten</button></div><label>Erst nach erfolgreichem Health-Test: iCloud-Link<input id="healthLinkInput" type="url" placeholder="https://www.icloud.com/shortcuts/…"></label><button id="healthSaveLink">Link für Freunde speichern</button></div></div>`);const m=document.querySelector('#healthBuildModal');document.querySelector('#healthBuildClose').onclick=()=>close('healthBuildModal');m.onclick=e=>{if(e.target===m)close('healthBuildModal')};document.querySelector('#healthCopyPrefix').onclick=()=>copy(PREFIX);document.querySelector('#healthOpenBuild').onclick=()=>location.href='shortcuts://create-shortcut';document.querySelector('#healthLocalTest').onclick=()=>location.href=PREFIX+'4321&source=health';document.querySelector('#healthSaveLink').onclick=()=>{if(!saveLink(document.querySelector('#healthLinkInput').value)){toast('Bitte den iCloud-Link des fertigen „CutCoach Sync“ einfügen.');return}close('healthBuildModal');toast('Installationslink gespeichert.');render()}}
  function ensureInstall(){if(document.querySelector('#healthInstallModal'))return;document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="healthInstallModal"><div class="sheet health-wizard-sheet"><div class="sheet-head"><div><h2>Apple Health verbinden</h2><small>Fertiger Kurzbefehl</small></div><button id="healthInstallClose">×</button></div><h3>„CutCoach Sync“ installieren</h3><p>Tippe auf den Button, füge den Kurzbefehl hinzu und starte ihn einmal. Erlaube dabei den Zugriff auf Schritte.</p><button id="healthInstallReal"> Kurzbefehl installieren</button><button class="secondary" id="healthCheckReal">Verbindung prüfen</button><div class="health-check-result" id="healthRealResult" hidden></div></div></div>`);const m=document.querySelector('#healthInstallModal');document.querySelector('#healthInstallClose').onclick=()=>close('healthInstallModal');m.onclick=e=>{if(e.target===m)close('healthInstallModal')};document.querySelector('#healthInstallReal').onclick=()=>location.href=localStorage.getItem(LINK);document.querySelector('#healthCheckReal').onclick=()=>{const r=document.querySelector('#healthRealResult');r.hidden=false;r.className='health-check-result '+(connected()?'success':'pending');r.innerHTML=connected()?'<strong>✓ Verbunden</strong><span>Health-Schritte wurden übernommen.</span>':'<strong>Noch kein Health-Sync</strong><span>Der Kurzbefehl wurde noch nicht ausgeführt oder enthält nicht die fünf benötigten Aktionen.</span>'}}
  function renderCard(){ensureCard();const c=document.querySelector('#healthPremiumCard'),meta=read(SYNC),entry=meta.days?.[selectedDate]||(selectedDate===todayKey()?meta.last:null),ok=Boolean(entry);c.dataset.state=ok?'connected':'disconnected';document.querySelector('#healthPremiumTitle').textContent=ok?'Apple Health verbunden':linked()?'Apple Health verbinden':'CutCoach Sync noch nicht erstellt';document.querySelector('#healthPremiumText').textContent=ok?'Dein Schrittstand wurde übernommen.':linked()?'Der fertige Kurzbefehl kann jetzt installiert werden.':'Zuerst muss einmal der echte Health-Kurzbefehl erstellt werden.';document.querySelector('#healthPremiumAction').textContent=ok?'Verbindung ansehen':linked()?'Jetzt verbinden':'Kurzbefehl richtig erstellen';const box=document.querySelector('#healthPremiumMeta');box.hidden=!ok;if(ok){document.querySelector('#healthPremiumSteps').textContent=fmt(entry.steps)+' Schritte';document.querySelector('#healthPremiumTime').textContent=new Date(entry.syncedAt).toLocaleString('de-DE',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}}
  function post(){ensureBuild();ensureInstall();renderCard();const v=document.querySelector('#appVersion');if(v)v.textContent='Version '+VERSION}
  window.render=function(){baseRender();post()};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>window.render(),{once:true});else window.render();
})();