'use strict';
(function(){
  const VERSION='5.8.0';
  const WATER_KEY='cutcoach_water_v1';
  const WATER_UNDO_KEY='cutcoach_water_undo_v3';
  const WATER_TARGET=3000;
  const WATER_MAX=6000;
  const fmt0=value=>new Intl.NumberFormat('de-DE',{maximumFractionDigits:0}).format(Math.max(0,Number(value)||0));
  const fmt1=value=>new Intl.NumberFormat('de-DE',{minimumFractionDigits:1,maximumFractionDigits:1}).format(Math.max(0,Number(value)||0));
  const clampJournal=(value,min,max)=>Math.min(max,Math.max(min,Number(value)||0));
  function safeJson(storage,key,fallback={}){try{const value=JSON.parse(storage.getItem(key)||'null');return value&&typeof value==='object'&&!Array.isArray(value)?value:fallback}catch{return fallback}}
  function waterMap(){return safeJson(localStorage,WATER_KEY,{})}
  function waterFor(key=selectedDate){return Math.round(clampJournal(waterMap()[key]||0,0,WATER_MAX))}
  function waterPace(key=selectedDate){if(key!==todayKey())return key<todayKey()?WATER_TARGET:0;const now=new Date(),hour=now.getHours()+now.getMinutes()/60;return Math.round(clampJournal((hour-7)/15,.08,1)*WATER_TARGET/250)*250}
  function undoRecord(){return safeJson(sessionStorage,WATER_UNDO_KEY,null)}
  function storeUndo(record){try{sessionStorage.setItem(WATER_UNDO_KEY,JSON.stringify(record))}catch{}}
  function clearUndo(){try{sessionStorage.removeItem(WATER_UNDO_KEY)}catch{}}
  function writeWater(next,remember=true){const previous=waterFor(),requested=Math.round(Number(next)||0),amount=Math.round(clampJournal(requested,0,WATER_MAX)),all=waterMap();if(remember&&amount!==previous)storeUndo({date:selectedDate,previous,current:amount,at:Date.now()});if(amount)all[selectedDate]=amount;else delete all[selectedDate];try{localStorage.setItem(WATER_KEY,JSON.stringify(all));if(requested>WATER_MAX)toast?.('Maximal 6.000 ml pro Tag eintragbar.');navigator.vibrate?.(10);window.render()}catch{toast?.('Wasser konnte nicht gespeichert werden.')}}
  function undoWater(){const record=undoRecord();if(!record||record.date!==selectedDate||Number(record.current)!==waterFor())return;clearUndo();writeWater(record.previous,false);toast?.('Letzte Wasseränderung zurückgenommen.')}
  function hasDiaryEntry(key){const data=day(key,false);return Boolean(data.meals?.length||data.steps!==null||data.weight!==null||data.gym!==null||data.alcohol!==null||waterFor(key)>0)}
  function streakState(){const today=todayKey(),todayDone=hasDiaryEntry(today),start=todayDone?today:shiftKey(today,-1);let count=0,cursor=dateFromKey(start);for(let index=0;index<366;index++){const key=keyFromDate(cursor);if(!hasDiaryEntry(key))break;count++;cursor.setDate(cursor.getDate()-1)}return{count,pending:!todayDone&&count>0}}
  function activityEstimate(data){const steps=data.steps===null?0:Number(data.steps)||0;return Math.max(0,Math.round(steps*.04)+(data.gym===true?180:0))}
  function ensureStructure(){
    const root=document.querySelector('#today560');if(!root)return null;const top=root.querySelector('.journal-topbar');
    if(top&&!root.querySelector('.journal-day-controls')){const controls=document.createElement('div');controls.className='journal-day-controls';controls.innerHTML='<button id="journalPrevDay" type="button" aria-label="Vorheriger Tag">‹</button><button id="journalNextDay" type="button" aria-label="Nächster Tag">›</button>';top.insertBefore(controls,root.querySelector('.journal-mini-stats'));controls.querySelector('#journalPrevDay').onclick=()=>document.querySelector('#previousDay')?.click();controls.querySelector('#journalNextDay').onclick=()=>document.querySelector('#nextDay')?.click()}
    if(top&&!root.querySelector('.journal-topbar-tools')){const tools=document.createElement('div');tools.className='journal-topbar-tools';['.journal-day-controls','.journal-mini-stats','.journal-calendar-button'].forEach(selector=>{const node=top.querySelector(selector);if(node)tools.append(node)});top.append(tools)}
    root.querySelector('#journalDateButton i')?.remove();const calendar=root.querySelector('#journalCalendarButton');
    if(calendar){calendar.textContent='';let input=calendar.querySelector('.journal-calendar-input');if(!input){input=document.createElement('input');input.type='date';input.className='journal-calendar-input';input.setAttribute('aria-label','Datum auswählen');calendar.append(input);input.addEventListener('change',()=>{if(input.value)selectDate(input.value)})}input.max=todayKey();input.value=selectedDate;calendar.onclick=null;calendar.title='Datum auswählen'}
    const dateButton=root.querySelector('#journalDateButton');if(dateButton){dateButton.title='Datum auswählen';dateButton.onclick=()=>{const input=root.querySelector('.journal-calendar-input');try{input?.showPicker?.();return}catch{}input?.focus({preventScroll:true});input?.click()}}
    const mealTitle=root.querySelector('.journal-meals-card .journal-section-title>div');if(mealTitle&&!root.querySelector('#journalMealSummary')){const summary=document.createElement('small');summary.id='journalMealSummary';summary.className='journal-meal-summary';mealTitle.append(summary)}
    const weightCard=root.querySelector('.journal-check-grid article:first-child');if(weightCard&&!root.querySelector('#journalWeightMeta')){const meta=document.createElement('small');meta.id='journalWeightMeta';meta.className='journal-weight-meta';weightCard.querySelector('strong')?.after(meta)}
    root.querySelector('#journalSteps')?.classList.add('journal-step-value');root.querySelector('#journalCheckStatus')?.classList.add('journal-check-status');root.querySelector('#journalCoachText')?.setAttribute('aria-live','polite');root.querySelector('#journalCheckStatus')?.setAttribute('aria-live','polite');root.querySelector('#journalWaterHint')?.setAttribute('aria-live','polite');const activityLabel=root.querySelector('.journal-energy-stats article:last-child small');if(activityLabel)activityLabel.textContent='Aktivität';const activityCard=root.querySelector('.journal-energy-stats article:last-child');if(activityCard)activityCard.title='Geschätzter Aktivitätsverbrauch aus Schritten und Training. Das feste Kalorienziel wird dadurch nicht automatisch erhöht.';configureSteps(root);configureWater(root);configureWeight(root);return root;
  }
  function configureSteps(root){const toggle=root.querySelector('#journalStepToggle'),editor=root.querySelector('#journalStepEditor'),input=root.querySelector('#journalStepInput'),save=root.querySelector('#journalStepSave'),clear=root.querySelector('#journalStepClear');if(!toggle||toggle.dataset.consolidated)return;toggle.dataset.consolidated='1';toggle.setAttribute('aria-expanded','false');const sync=()=>{const raw=String(input.value??'').trim(),parsed=Number(raw),current=day(selectedDate,false).steps;save.disabled=raw===''||!Number.isFinite(parsed)||parsed<0||parsed>100000||Math.round(parsed)!==parsed||String(current??'')===raw};toggle.onclick=()=>{editor.hidden=!editor.hidden;toggle.setAttribute('aria-expanded',String(!editor.hidden));if(!editor.hidden){input.value=day(selectedDate,false).steps??'';sync();setTimeout(()=>input.focus(),30)}};input.addEventListener('input',sync);input.addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();save.click()}if(event.key==='Escape'){editor.hidden=true;toggle.setAttribute('aria-expanded','false')}});save.onclick=()=>{const parsed=Number(String(input.value).trim());if(!Number.isInteger(parsed)||parsed<0||parsed>100000){toast?.('Bitte ganze Schritte zwischen 0 und 100.000 eingeben.');return}const original=document.querySelector('#stepsInput');if(!original)return;original.value=String(parsed);document.querySelector('#saveSteps')?.click();editor.hidden=true;toggle.setAttribute('aria-expanded','false')};clear.onclick=()=>{document.querySelector('#clearSteps')?.click();editor.hidden=true;toggle.setAttribute('aria-expanded','false')}}
  function configureWater(root){if(root.dataset.waterConsolidated)return;root.dataset.waterConsolidated='1';root.querySelectorAll('[data-journal-water]').forEach(button=>button.onclick=()=>writeWater(waterFor()+Number(button.dataset.journalWater)));const undo=root.querySelector('#journalWaterUndo');if(undo)undo.onclick=undoWater}
  function configureWeight(root){const button=root.querySelector('#journalWeightButton');if(!button||button.dataset.consolidated)return;button.dataset.consolidated='1';button.onclick=()=>{const data=day(selectedDate,false),input=document.querySelector('#weightInput'),clear=document.querySelector('#clearWeight');if(input)input.value=data.weight??'';if(clear)clear.hidden=data.weight===null;openModal?.('weightModal')}}
  function refresh(){
    const root=ensureStructure();if(!root)return;const data=day(selectedDate,false),settings=state.settings,total=totals(),date=dateFromKey(selectedDate),isToday=selectedDate===todayKey(),remaining=settings.calories-total.calories,rawPct=settings.calories>0?total.calories/settings.calories*100:0,score=typeof dailyScore==='function'?dailyScore():null;
    root.querySelector('#journalWeekday').textContent=isToday?'Heute':date.toLocaleDateString('de-DE',{weekday:'long'});root.querySelector('#journalDate').textContent=date.toLocaleDateString('de-DE',{weekday:'long',day:'numeric',month:'long',year:'numeric'});const dateInput=root.querySelector('.journal-calendar-input');if(dateInput){dateInput.max=todayKey();dateInput.value=selectedDate}const next=root.querySelector('#journalNextDay');if(next)next.disabled=isToday;
    const ring=root.querySelector('#journalCalorieRing');if(ring){ring.style.setProperty('--journal-calories',`${clampJournal(rawPct,0,100)*3.6}deg`);ring.classList.toggle('over',remaining<0);ring.classList.toggle('near',remaining>=0&&remaining<=200);ring.classList.toggle('empty',total.calories===0);ring.setAttribute('aria-label',`${fmt0(total.calories)} von ${fmt0(settings.calories)} Kilokalorien gegessen`)}
    const scoreNode=root.querySelector('#journalScore');if(scoreNode)scoreNode.textContent=score===null?'–':fmt1(score);const streak=streakState(),fire=root.querySelector('#journalGym');if(fire){fire.textContent=String(streak.count);fire.closest('span')?.classList.toggle('pending',streak.pending);fire.closest('span')?.setAttribute('title',streak.pending?`${streak.count} Tage in Folge – heute fehlt noch ein Tagebucheintrag`:`${streak.count} Tage in Folge mit mindestens einem Tagebucheintrag`)}const activity=root.querySelector('#journalBurned');if(activity)activity.textContent=`${fmt0(activityEstimate(data))} kcal`;
    [['protein',total.protein,settings.protein],['carbs',total.carbs,settings.carbs],['fat',total.fat,settings.fat]].forEach(([key,value,goal])=>{const raw=goal>0?value/goal*100:(value>0?100:0),article=root.querySelector(`#${key}JournalText`)?.closest('article'),bar=root.querySelector(`#${key}JournalBar`),label=root.querySelector(`#${key}JournalPct`);if(bar)bar.style.width=`${clampJournal(raw,0,100)}%`;if(label)label.textContent=goal===0?(value===0?'–':`${fmt0(value)} g`):`${Math.round(raw)} %`;article?.classList.toggle('complete',goal>0&&raw>=90&&raw<=110);article?.classList.toggle('over',goal>0&&raw>110)});
    const mealCount=data.meals.length,mealSummary=root.querySelector('#journalMealSummary');if(mealSummary)mealSummary.textContent=mealCount?`${mealCount} ${mealCount===1?'Eintrag':'Einträge'} · ${fmt0(total.calories)} kcal`:'Noch leer';const ratios={'Frühstück':.30,'Mittagessen':.35,'Abendessen':.25,'Snack':.10};root.querySelectorAll('.journal-meal-row').forEach((row,index)=>{const type=MEAL_TYPES[index],current=data.meals.filter(item=>item.type===type).reduce((sum,item)=>sum+(Number(item.calories)||0),0),goal=Math.round(settings.calories*(ratios[type]||.25));row.classList.toggle('filled',current>0);row.classList.toggle('complete',goal>0&&current>=goal*.85&&current<=goal*1.15);row.classList.toggle('over',goal>0&&current>goal*1.15)});
    const steps=data.steps===null?null:Number(data.steps)||0,stepGoal=Number(settings.steps)||0,stepCard=root.querySelector('.journal-steps-card'),stepMeta=root.querySelector('#journalStepMeta');stepCard?.classList.toggle('goal-reached',steps!==null&&(stepGoal===0||steps>=stepGoal));if(stepMeta){if(steps===null)stepMeta.textContent='Noch nicht eingetragen';else{const distance=fmt1(steps*.00075),calories=fmt0(Math.round(steps*.04));stepMeta.textContent=stepGoal>0&&steps<stepGoal?`Noch ${fmt0(stepGoal-steps)} bis Ziel · ${distance} km`:`Ziel erreicht · ${distance} km · ${calories} kcal`}}const stepInput=root.querySelector('#journalStepInput'),stepSave=root.querySelector('#journalStepSave');if(stepInput&&document.activeElement!==stepInput)stepInput.value=data.steps??'';if(stepSave&&document.activeElement!==stepInput)stepSave.disabled=true;
    const water=waterFor(),pace=waterPace(),waterCard=root.querySelector('.journal-water-card'),hint=root.querySelector('#journalWaterHint'),undo=root.querySelector('#journalWaterUndo'),record=undoRecord();waterCard?.classList.toggle('goal-reached',water>=WATER_TARGET);waterCard?.classList.toggle('on-pace',water<WATER_TARGET&&water>=pace);waterCard?.classList.toggle('behind',isToday&&water<pace-250);if(hint){if(water>=WATER_TARGET)hint.textContent=water>WATER_TARGET?`${fmt0(water-WATER_TARGET)} ml über dem Tagesziel.`:'Tagesziel erreicht – stark!';else if(isToday&&water>=pace)hint.textContent=`Im Trinkplan · noch ${fmt0(WATER_TARGET-water)} ml bis zum Tagesziel.`;else if(isToday&&water>0)hint.textContent=`Noch ${fmt0(Math.max(0,pace-water))} ml bis zum aktuellen Soll.`;else hint.textContent=water>0?`Noch ${fmt0(WATER_TARGET-water)} ml bis zum Tagesziel.`:'Starte mit dem ersten Glas.'}if(undo){const canUndo=Boolean(record&&record.date===selectedDate&&Number(record.current)===water);undo.disabled=!canUndo;undo.textContent=canUndo?'↶ Letzte Änderung':'↶ Rückgängig'}
    const todayWeight=data.weight,allWeights=weightEntries(selectedDate),previous=allWeights.filter(([key])=>key<selectedDate).at(-1),weight=root.querySelector('#journalWeight'),weightMeta=root.querySelector('#journalWeightMeta');if(weight)weight.textContent=todayWeight===null?'– kg':`${fmt1(todayWeight)} kg`;if(weightMeta)weightMeta.textContent=todayWeight!==null?'Für diesen Tag':previous?`Zuletzt ${dateFromKey(previous[0]).toLocaleDateString('de-DE',{day:'2-digit',month:'2-digit'})}: ${fmt1(previous[1].weight)} kg`:'Noch kein Messwert';const weightButton=root.querySelector('#journalWeightButton');if(weightButton)weightButton.textContent=todayWeight===null?'Eintragen':'Ändern';
    const completed=[todayWeight!==null,data.gym!==null,data.alcohol!==null].filter(Boolean).length,check=root.querySelector('#journalCheckStatus'),checkCard=root.querySelector('.journal-check-card');if(check){check.textContent=completed===3?'Vollständig':`${completed}/3 Angaben`;check.classList.toggle('complete',completed===3);check.classList.toggle('partial',completed>0&&completed<3)}checkCard?.classList.toggle('complete',completed===3);root.querySelectorAll('[data-journal-gym]').forEach(button=>{const active=String(data.gym)===button.dataset.journalGym;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active))});root.querySelectorAll('[data-journal-alcohol]').forEach(button=>{const active=String(data.alcohol)===button.dataset.journalAlcohol;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active))});
    const coach=root.querySelector('.journal-coach-card'),scoreLarge=root.querySelector('#journalScoreLarge'),coachTitle=root.querySelector('#journalCoachTitle');if(scoreLarge)scoreLarge.textContent=score===null?'–':fmt1(score);if(coachTitle)coachTitle.textContent=isToday?(total.calories?'Dein nächster sinnvoller Schritt':'Bereit für deinen Tag'):(total.calories?'Rückblick auf diesen Tag':'Noch keine Einträge');coach?.classList.toggle('strong',score!==null&&score>=8);coach?.classList.toggle('attention',score!==null&&score<6);const version=document.querySelector('#appVersion');if(version)version.textContent=`Version ${VERSION}`;
  }
  const base=window.render;window.render=function(){base();refresh()};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(refresh,220),{once:true});else setTimeout(refresh,220);
})();
