'use strict';
(function(){
  const VERSION='7.3.2';
  const $=(selector,scope=document)=>scope.querySelector(selector);
  const normalize=value=>String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('de').replace(/ß/g,'ss').replace(/[^a-z0-9]+/g,' ').trim().replace(/\s+/g,' ');
  const fmt=(value,digits=0)=>new Intl.NumberFormat('de-DE',{minimumFractionDigits:digits,maximumFractionDigits:digits}).format(Math.max(0,Number(value)||0));
  const escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
  let root=null,results=null,observer=null,scheduled=false,enhancing=false,inputTimer=0,lastQuery='';
  function everydayItems(){try{return window.CutCoachEverydayCatalog?.items?.()||[]}catch{return[]}}
  function everydayByName(name){const key=normalize(name);return everydayItems().find(item=>normalize(item.name)===key)||null}
  function icon(item){return item.category==='Bäckerei'?'🥨':item.category==='Imbiss'?'🥙':item.category==='Fast Food'?'🍔':item.category==='Kantine'?'🍽️':item.category==='Frühstück'?'🥣':'🍎'}
  function removeRedundantUi(){
    $('#nutritionEverydayQuick',root)?.remove();
    const coachText=$('#journalCoachText');if(coachText){coachText.textContent='';coachText.hidden=true;coachText.style.display='none'}
    const note=$('.nutrition-catalog-note',root);if(note&&!note.dataset.v73){note.dataset.v73='1';note.insertAdjacentHTML('beforeend',' · <span>CutCoach-Standardgerichte aus BLS-Zutaten</span>')}
  }
  function matchingItems(query){const q=normalize(query),tokens=q.split(/\s+/).filter(Boolean);if(!tokens.length)return[];return everydayItems().map(item=>{const aliases=(item.aliases||[]).map(normalize),name=normalize(item.name),search=`${name} ${aliases.join(' ')}`;if(!tokens.every(token=>search.includes(token)))return null;let score=name===q?1000:aliases.includes(q)?900:name.startsWith(q)?600:300;for(const token of tokens)if(name.split(' ').some(word=>word.startsWith(token)))score+=70;return{item,score}}).filter(Boolean).sort((a,b)=>b.score-a.score||a.item.name.localeCompare(b.item.name,'de')).slice(0,12).map(entry=>entry.item)}
  function resultHtml(item){const amount=Number(item.amount)||100,unit=item.unit||'g',capacity=typeof mealCapacity==='function'?mealCapacity():1,meal=document.body.dataset.nutritionMealType||$('#nutritionMealSelect',root)?.value||'Mahlzeit';return `<article class="nutrition-result-row v73-everyday-row" data-v73-query="${escapeHtml(lastQuery)}"><button class="nutrition-result-main" type="button" data-nutrition-open="${escapeHtml(item.id)}" aria-label="${escapeHtml(item.name)}, Portion auswählen"><span class="nutrition-result-icon" aria-hidden="true">${icon(item)}</span><span class="nutrition-result-copy"><b><span title="${escapeHtml(item.name)}">${escapeHtml(item.name)}</span><i class="nutrition-source standard" aria-label="CutCoach Standardgericht aus BLS-Zutaten">Standard</i></b><small>${fmt(amount,amount%1?1:0)} ${escapeHtml(unit)} · E ${fmt(item.protein,1)} · KH ${fmt(item.carbs,1)} · F ${fmt(item.fat,1)}</small></span></button><span class="nutrition-result-energy"><b>${fmt(item.calories)} kcal</b></span><button class="nutrition-result-add" type="button" data-nutrition-add="${escapeHtml(item.id)}" aria-label="${escapeHtml(item.name)}, direkt zu ${escapeHtml(meal)} hinzufügen" ${capacity<1?'disabled':''}>＋</button></article>`}
  function clearInjected(){results?.querySelectorAll('.v73-everyday-row').forEach(node=>node.remove())}
  function enhanceResults(){const input=$('#nutritionSearch',root),host=$('#nutritionResults',root);if(!input||!host)return;results=host;const query=input.value.trim(),normalizedQuery=normalize(query);if(!normalizedQuery){lastQuery='';clearInjected();return}if(normalizedQuery!==lastQuery){lastQuery=normalizedQuery;clearInjected()}const existing=new Set([...host.querySelectorAll('[data-nutrition-open]')].map(node=>node.dataset.nutritionOpen));const missing=matchingItems(query).filter(item=>!existing.has(item.id));if(!missing.length)return;host.querySelector('.nutrition-empty')?.remove();host.classList.remove('is-empty');host.insertAdjacentHTML('afterbegin',missing.map(resultHtml).join(''));const count=$('#nutritionResultCount',root);if(count){const total=host.querySelectorAll('.nutrition-result-row').length;count.textContent=`${fmt(total)} Treffer`}}
  function decorate(){const scope=$('#nutritionResultScope',root),input=$('#nutritionSearch',root);if(scope&&input?.value.trim())scope.textContent='Bibliothek, BLS & Alltagsgerichte';root.querySelectorAll('.nutrition-result-row [data-nutrition-open^="ccde:"]').forEach(button=>{const title=button.querySelector('.nutrition-result-copy b');if(title&&!title.querySelector('.nutrition-source.standard'))title.insertAdjacentHTML('beforeend','<i class="nutrition-source standard" aria-label="CutCoach Standardgericht aus BLS-Zutaten">Standard</i>')});root.querySelectorAll('#recipeV7SearchResults [data-recipe-ingredient^="ccde:"]').forEach(button=>{const label=button.querySelector('span');if(label)label.textContent='Standard'});const detailTitle=$('#nutritionDetailTitle',root),source=$('#nutritionDetailSource',root);if(detailTitle&&source&&$('#nutritionDetailModal',root)?.classList.contains('open')){const item=everydayByName(detailTitle.textContent);if(item){const coverage=['fiber','sugar','saturatedFat','salt'].filter(key=>item[key]!==null&&item[key]!==undefined).length;source.dataset.source='cutcoach';source.innerHTML=`<span>CutCoach Standardgericht · aus BLS 4.0 berechnet</span><small>Standardportion ${fmt(item.amount,item.amount%1?1:0)} ${escapeHtml(item.unit||'g')} · ${coverage}/4 Zusatzwerte vorhanden</small>`}}}
  function sync(){if(enhancing||!root?.isConnected)return;enhancing=true;try{removeRedundantUi();enhanceResults();decorate()}finally{enhancing=false}}
  function queueSync(){if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;sync()})}
  function onInput(event){if(event.target?.id!=='nutritionSearch')return;clearTimeout(inputTimer);inputTimer=setTimeout(queueSync,180)}
  function start(found){root=found;results=$('#nutritionResults',root);observer=new MutationObserver(records=>{if(records.some(record=>record.addedNodes.length||record.removedNodes.length))queueSync()});observer.observe(root,{childList:true,subtree:true});root.addEventListener('input',onInput,{passive:true});root.addEventListener('change',queueSync,{passive:true});root.addEventListener('click',queueSync,true);queueSync()}
  function boot(){const found=document.querySelector('[data-screen="food"]');if(found){start(found);return}const bootstrap=new MutationObserver(()=>{const node=document.querySelector('[data-screen="food"]');if(!node)return;bootstrap.disconnect();start(node)});bootstrap.observe(document.body||document.documentElement,{childList:true,subtree:true})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
  window.CutCoachNutritionV73=Object.freeze({version:VERSION,refresh:queueSync,matching:matchingItems});
})();