'use strict';
(function(){
  const VERSION='6.0.1';
  const LIBRARY_KEY='cutcoach_library_v1';
  let mealType='Frühstück';
  let activeFilter='all';
  let recognition=null;

  function readLibrary(){try{const parsed=JSON.parse(localStorage.getItem(LIBRARY_KEY)||'{}');return Array.isArray(parsed?.items)?parsed.items:[]}catch{return []}}
  function fmt(value,digits=0){return new Intl.NumberFormat('de-DE',{maximumFractionDigits:digits,minimumFractionDigits:digits}).format(Math.max(0,Number(value)||0))}
  function escapeHtml(value){return String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
  function currentDay(){return typeof day==='function'?day(selectedDate,false):{meals:[]}}

  function activateScreen(name){
    document.querySelectorAll('[data-tab]').forEach(button=>{const on=button.dataset.tab===name;button.classList.toggle('active',on);button.setAttribute('aria-current',on?'page':'false')});
    document.querySelectorAll('.screen').forEach(screen=>screen.classList.toggle('active',screen.dataset.screen===name));
  }
  function openFoodScreen(type=mealType){mealType=type||'Frühstück';activateScreen('food');document.body.classList.remove('journal-mode');document.body.classList.add('nutrition-mode');window.scrollTo({top:0,behavior:'auto'});renderNutrition()}
  function leaveNutrition(){document.body.classList.remove('nutrition-mode');stopVoice()}
  function goBack(){activateScreen('today');leaveNutrition();document.body.classList.add('journal-mode');history.replaceState(null,'','#today');window.scrollTo({top:0,behavior:'auto'});window.render?.()}

  function ensureStructure(){
    const screen=document.querySelector('[data-screen="food"]');if(!screen||screen.dataset.nutritionReady)return screen;
    screen.dataset.nutritionReady='1';
    screen.innerHTML=`<div class="nutrition-shell">
      <header class="nutrition-header-card">
        <button id="nutritionBack" class="nutrition-back" type="button" aria-label="Zurück zum Tagebuch">‹</button>
        <div class="nutrition-header-copy"><h1 id="nutritionTitle">Frühstück</h1><p>Lebensmittel suchen und direkt eintragen</p></div>
        <button id="nutritionManual" class="nutrition-manual" type="button">＋ Manuell</button>
      </header>
      <section class="nutrition-search-card">
        <label class="nutrition-search-row" for="nutritionSearch"><span aria-hidden="true">⌕</span><input id="nutritionSearch" type="search" autocomplete="off" enterkeyhint="search" placeholder="Lebensmittel, Gericht oder Marke"><button id="nutritionVoice" type="button" aria-label="Spracheingabe starten">🎤</button></label>
        <p id="nutritionVoiceStatus" aria-live="polite">Suche in deiner Bibliothek oder nutze Barcode und Sprache.</p>
      </section>
      <section class="nutrition-actions" aria-label="Schnellaktionen">
        <button id="nutritionBarcode" type="button"><span>▣</span><b>Barcode</b><small>Produkt scannen</small></button>
        <button id="nutritionRecipe" type="button"><span>🍽️</span><b>Rezept</b><small>Eigenes Gericht</small></button>
        <button id="nutritionNewFood" type="button"><span>＋</span><b>Lebensmittel</b><small>Selbst anlegen</small></button>
      </section>
      <section class="nutrition-tabs" role="tablist" aria-label="Lebensmittelauswahl"><button class="active" data-nutrition-filter="all" type="button">Alle</button><button data-nutrition-filter="favorite" type="button">Favoriten</button><button data-nutrition-filter="recent" type="button">Zuletzt</button><button data-nutrition-filter="dish" type="button">Rezepte</button></section>
      <section class="nutrition-overview-card"><div><small id="nutritionMealLabel">Frühstück</small><strong id="nutritionMealKcal">0 kcal</strong></div><div><small>Einträge</small><strong id="nutritionMealCount">0</strong></div><button id="nutritionCopyPrevious" type="button">Vortag übernehmen</button></section>
      <section class="nutrition-section-head"><div><small>Bibliothek</small><h2 id="nutritionResultTitle">Schnelle Auswahl</h2></div></section>
      <div id="nutritionResults" class="nutrition-results"></div>
      <section class="nutrition-current"><div class="nutrition-section-head"><div><small>Diese Mahlzeit</small><h2>Bereits eingetragen</h2></div></div><div id="nutritionCurrentMeals"></div></section>
    </div>`;
    screen.querySelector('#nutritionBack').onclick=goBack;screen.querySelector('#nutritionManual').onclick=openManual;screen.querySelector('#nutritionNewFood').onclick=()=>openLibraryEditor('food');screen.querySelector('#nutritionRecipe').onclick=()=>openLibraryEditor('dish');screen.querySelector('#nutritionBarcode').onclick=openScanner;screen.querySelector('#nutritionCopyPrevious').onclick=()=>document.querySelector('#copyPreviousMeals')?.click();screen.querySelector('#nutritionSearch').addEventListener('input',renderResults);screen.querySelector('#nutritionSearch').addEventListener('search',renderResults);screen.querySelector('#nutritionVoice').onclick=startVoice;screen.querySelectorAll('[data-nutrition-filter]').forEach(button=>button.onclick=()=>{activeFilter=button.dataset.nutritionFilter;screen.querySelectorAll('[data-nutrition-filter]').forEach(item=>item.classList.toggle('active',item===button));renderResults()});return screen;
  }
  function openManual(){const type=document.querySelector('#mealType');if(type)type.value=mealType;openModal?.('mealModal')}
  function openScanner(){const button=document.querySelector('#scanCode');if(button){button.click();return}toast?.('Scanner wird noch geladen. Bitte kurz erneut versuchen.')}
  function openLibraryEditor(kind){const button=document.querySelector('#newLibraryItem');if(!button){toast?.('Bibliothek wird noch geladen. Bitte kurz erneut versuchen.');return}button.click();if(kind==='dish')setTimeout(()=>document.querySelector('[data-kind="dish"]')?.click(),40)}
  function useLibraryItem(id){const selector=`[data-use-lib="${CSS.escape(id)}"]`,button=document.querySelector(selector);if(!button){toast?.('Eintrag konnte nicht geöffnet werden.');return}button.click();setTimeout(()=>{const select=document.querySelector('#libraryMealType');if(select)select.value=mealType},50)}
  function stopVoice(){if(!recognition)return;try{recognition.abort()}catch{}recognition=null;document.querySelector('#nutritionVoice')?.classList.remove('listening')}
  function startVoice(){const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition,status=document.querySelector('#nutritionVoiceStatus'),input=document.querySelector('#nutritionSearch'),button=document.querySelector('#nutritionVoice');if(!SpeechRecognition){status.textContent='Tippe ins Suchfeld und nutze das Mikrofon der iPhone-Tastatur.';input?.focus();toast?.('Nutze die Diktierfunktion unten auf der iPhone-Tastatur.');return}stopVoice();recognition=new SpeechRecognition();recognition.lang='de-DE';recognition.continuous=false;recognition.interimResults=true;recognition.maxAlternatives=3;button?.classList.add('listening');status.textContent='Ich höre zu …';recognition.onresult=event=>{let transcript='';for(let i=event.resultIndex;i<event.results.length;i++)transcript+=`${event.results[i][0].transcript} `;transcript=transcript.trim();if(transcript){input.value=transcript;input.dispatchEvent(new Event('input',{bubbles:true}));status.textContent=`Erkannt: „${transcript}“`;if(event.results[event.results.length-1].isFinal)setTimeout(()=>input.focus(),80)}};recognition.onerror=event=>{const message=event.error==='not-allowed'?'Mikrofonzugriff wurde blockiert. Nutze die iPhone-Diktierfunktion.':event.error==='no-speech'?'Keine Sprache erkannt. Tippe erneut auf das Mikrofon.':'Spracheingabe konnte nicht gestartet werden.';status.textContent=message;button?.classList.remove('listening')};recognition.onend=()=>{button?.classList.remove('listening');recognition=null;if(!input.value.trim())status.textContent='Keine Sprache erkannt. Tippe erneut oder nutze die Tastatur.'};try{recognition.start()}catch{status.textContent='Spracheingabe ist gerade nicht verfügbar. Nutze die iPhone-Diktierfunktion.';input?.focus();button?.classList.remove('listening')}}
  function renderResults(){const host=document.querySelector('#nutritionResults');if(!host)return;const query=String(document.querySelector('#nutritionSearch')?.value||'').trim().toLocaleLowerCase('de');let items=readLibrary();if(query)items=items.filter(item=>`${item.name||''} ${item.barcode||''}`.toLocaleLowerCase('de').includes(query));if(activeFilter==='favorite')items=items.filter(item=>item.favorite);if(activeFilter==='recent')items=items.filter(item=>item.lastUsedAt).sort((a,b)=>String(b.lastUsedAt).localeCompare(String(a.lastUsedAt)));else if(activeFilter==='dish')items=items.filter(item=>item.kind==='dish');else items.sort((a,b)=>Number(b.favorite)-Number(a.favorite)||(b.uses||0)-(a.uses||0)||String(a.name).localeCompare(String(b.name),'de'));document.querySelector('#nutritionResultTitle').textContent=query?`Treffer für „${query}“`:activeFilter==='favorite'?'Deine Favoriten':activeFilter==='recent'?'Zuletzt verwendet':activeFilter==='dish'?'Deine Rezepte':'Schnelle Auswahl';if(!items.length){host.innerHTML=`<article class="nutrition-empty"><span>${query?'⌕':'🥣'}</span><b>${query?'Kein passender Eintrag':'Deine Bibliothek ist noch leer'}</b><p>${query?'Lege das Lebensmittel selbst an oder scanne den Barcode.':'Speichere häufige Lebensmittel und eigene Rezepte für den schnellen Zugriff.'}</p><button type="button" id="nutritionEmptyAdd">＋ Eintrag anlegen</button></article>`;host.querySelector('#nutritionEmptyAdd').onclick=()=>openLibraryEditor('food');return}host.innerHTML=items.slice(0,80).map(item=>`<article class="nutrition-result-card"><button class="nutrition-result-main" type="button" data-nutrition-use="${escapeHtml(item.id)}"><span class="nutrition-result-icon">${item.kind==='dish'?'🍽️':'🥫'}</span><span><b>${escapeHtml(item.name)}</b><small>${fmt(item.calories)} kcal · ${fmt(item.protein,1)} g Eiweiß · ${fmt(item.amount,item.amount%1?1:0)} ${escapeHtml(item.unit||'g')}</small></span></button><button class="nutrition-result-add" type="button" data-nutrition-use="${escapeHtml(item.id)}" aria-label="${escapeHtml(item.name)} hinzufügen">＋</button></article>`).join('');host.querySelectorAll('[data-nutrition-use]').forEach(button=>button.onclick=()=>useLibraryItem(button.dataset.nutritionUse))}
  function renderCurrent(){const host=document.querySelector('#nutritionCurrentMeals');if(!host)return;const meals=(currentDay().meals||[]).filter(item=>item.type===mealType),calories=meals.reduce((sum,item)=>sum+(Number(item.calories)||0),0);document.querySelector('#nutritionMealLabel').textContent=mealType;document.querySelector('#nutritionMealKcal').textContent=`${fmt(calories)} kcal`;document.querySelector('#nutritionMealCount').textContent=String(meals.length);if(!meals.length){host.innerHTML='<article class="nutrition-current-empty">Für diese Mahlzeit ist noch nichts eingetragen.</article>';return}host.innerHTML=meals.map(item=>`<article class="nutrition-current-row"><span>✓</span><div><b>${escapeHtml(item.name)}</b><small>${fmt(item.calories)} kcal · E ${fmt(item.protein,1)} · KH ${fmt(item.carbs,1)} · F ${fmt(item.fat,1)}</small></div></article>`).join('')}
  function renderNutrition(){const screen=ensureStructure();if(!screen)return;screen.querySelector('#nutritionTitle').textContent=mealType;renderResults();renderCurrent();const version=document.querySelector('#appVersion');if(version)version.textContent=`Version ${VERSION}`}
  function cleanNavigation(){document.querySelector('nav [data-tab="food"]')?.remove();document.querySelector('nav [data-tab="library"]')?.remove();document.querySelectorAll('.journal-section-title button,.journal-section-title a').forEach(node=>{if(node.textContent.trim().toLocaleLowerCase('de').includes('alle anzeigen'))node.remove()});document.querySelectorAll('nav [data-tab]').forEach(button=>button.addEventListener('click',()=>{if(button.dataset.tab!=='food')leaveNutrition()}))}
  document.addEventListener('click',event=>{const add=event.target.closest('[data-add-journal-meal]');if(add){event.preventDefault();event.stopImmediatePropagation();openFoodScreen(add.dataset.addJournalMeal);return}if(event.target.closest('#journalQuickAdd')){event.preventDefault();event.stopImmediatePropagation();const hour=new Date().getHours();openFoodScreen(hour<11?'Frühstück':hour<16?'Mittagessen':hour<21?'Abendessen':'Snack')}},true);
  const baseRender=window.render;window.render=function(){baseRender();cleanNavigation();if(document.querySelector('[data-screen="food"]')?.classList.contains('active'))renderNutrition()};document.addEventListener('DOMContentLoaded',()=>{ensureStructure();cleanNavigation()},{once:true});
})();