'use strict';
(function(){
  const VERSION='1.8.1-alpha';
  const API_V2='https://world.openfoodfacts.org/api/v2/product/';
  const API_V0='https://world.openfoodfacts.org/api/v0/product/';
  const FIELDS='code,product_name,product_name_de,generic_name,generic_name_de,brands,quantity,serving_size,nutrition_data_per,product_quantity_unit,serving_quantity_unit,categories_tags,nutriments,image_front_small_url,image_url';
  const OVERRIDE_KEY='cutcoach_library_overrides_v1',PROFILE_KEY='cutcoach_portion_profiles_v1';
  if(window.CutCoachOffLookup)return;
  let originalLookup=null,busy=false,resultItemId=null,lookupController=null,bootstrapObserver=null;
  const $=selector=>document.querySelector(selector);
  const cleanCode=value=>String(value||'').replace(/[^0-9A-Za-z._-]/g,'').slice(0,64);
  const escapeHtml=value=>String(value||'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
  function readOverrides(){try{const value=JSON.parse(localStorage.getItem(OVERRIDE_KEY)||'{}');return value&&typeof value==='object'&&!Array.isArray(value)?value:{}}catch{return{}}}
  function readProfiles(){try{const value=JSON.parse(localStorage.getItem(PROFILE_KEY)||'{}');return value&&typeof value==='object'&&!Array.isArray(value)?value:{}}catch{return{}}}
  function parsedNumber(value){if(typeof value==='string')value=value.replace(',','.').trim();if(value===null||value===undefined||value==='')return null;const n=Number(value);return Number.isFinite(n)&&n>=0?Math.round(n*100)/100:null}
  function firstAvailable(object,keys){for(const key of keys){const value=parsedNumber(object?.[key]);if(value!==null)return value}return null}
  function firstNumber(object,keys){return firstAvailable(object,keys)??0}
  function optionalFirstNumber(object,keys){return firstAvailable(object,keys)}
  function parsePortion(text){const match=String(text||'').toLocaleLowerCase('de').match(/(\d+(?:[.,]\d+)?)\s*(kg|g|ml|cl|dl|l|stück|stueck|portion)/);if(!match)return null;let amount=Number(match[1].replace(',','.')),unit=match[2];if(unit==='kg'){amount*=1000;unit='g'}else if(unit==='cl'){amount*=10;unit='ml'}else if(unit==='dl'){amount*=100;unit='ml'}else if(unit==='l'){amount*=1000;unit='ml'}else if(unit==='stück'||unit==='stueck')unit='Stück';else if(unit==='portion')unit='Portion';return amount>0?{amount:Math.round(amount*100)/100,unit}:null}
  function basisUnit(product){const serving=parsePortion(product?.serving_size),pack=parsePortion(product?.quantity),nutriments=product?.nutriments||{};if(serving?.unit==='ml'||pack?.unit==='ml')return'ml';if(String(product?.nutrition_data_per||'').toLowerCase().includes('volume'))return'ml';if(String(product?.product_quantity_unit||'').toLowerCase()==='ml'||String(product?.serving_quantity_unit||'').toLowerCase()==='ml')return'ml';if(Object.keys(nutriments).some(key=>/_100ml$/.test(key)))return'ml';if((product?.categories_tags||[]).some(tag=>/beverage|drink|soft-drink|energy-drink|juice/.test(String(tag))))return'ml';return'g'}
  function savePortionProfile(code,product){const serving=parsePortion(product?.serving_size),pack=parsePortion(product?.quantity);if(!serving&&!pack)return;const profiles=readProfiles();profiles[code]={servingAmount:serving?.amount||null,servingUnit:serving?.unit||null,packageAmount:pack?.amount||null,packageUnit:pack?.unit||null,updatedAt:new Date().toISOString(),source:'off'};try{localStorage.setItem(PROFILE_KEY,JSON.stringify(profiles))}catch{}}
  function status(text,state='info'){const node=$('#scannerStatus');if(node){node.textContent=text;node.dataset.state=state}}
  function productName(product){const name=String(product.product_name_de||product.product_name||product.generic_name_de||product.generic_name||'').trim(),brand=String(product.brands||'').split(',')[0].trim();if(name&&brand&&!name.toLowerCase().includes(brand.toLowerCase()))return`${brand} – ${name}`.slice(0,80);return(name||brand||'Unbekanntes Produkt').slice(0,80)}
  function nutrientKeys(base,unit){return unit==='ml'?[`${base}_100ml`,`${base}-100ml`,`${base}_100g`,`${base}-100g`,base]:[`${base}_100g`,`${base}-100g`,`${base}_100ml`,`${base}-100ml`,base]}
  function nutrition(product){const n=product?.nutriments||product?.nutritional_data||{},unit=basisUnit(product),calorieKeys=unit==='ml'?['energy-kcal_100ml','energy_kcal_100ml','energy-kcal_100g','energy_kcal_100g','energy-kcal','energy_kcal']:['energy-kcal_100g','energy_kcal_100g','energy-kcal_100ml','energy_kcal_100ml','energy-kcal','energy_kcal'];let calories=firstAvailable(n,calorieKeys),available=calories!==null;if(calories===null){const kj=firstAvailable(n,unit==='ml'?['energy_100ml','energy-kj_100ml','energy_100g','energy-kj_100g','energy','energy-kj']:['energy_100g','energy-kj_100g','energy_100ml','energy-kj_100ml','energy','energy-kj']);if(kj!==null){calories=Math.round(kj/4.184*100)/100;available=true}}return{available,unit,calories:calories??0,protein:firstNumber(n,nutrientKeys('proteins',unit).concat(nutrientKeys('protein',unit))),carbs:firstNumber(n,nutrientKeys('carbohydrates',unit).concat(nutrientKeys('carbohydrate',unit))),fat:firstNumber(n,nutrientKeys('fat',unit).concat(nutrientKeys('fats',unit))),fiber:optionalFirstNumber(n,nutrientKeys('fiber',unit).concat(nutrientKeys('fibers',unit))),sugar:optionalFirstNumber(n,nutrientKeys('sugars',unit).concat(nutrientKeys('sugar',unit))),saturatedFat:optionalFirstNumber(n,nutrientKeys('saturated-fat',unit).concat(nutrientKeys('saturated_fat',unit))),salt:optionalFirstNumber(n,nutrientKeys('salt',unit))}}
  const useful=value=>Boolean(value.available);
  async function requestJson(url,signal){const controller=new AbortController(),abort=()=>controller.abort(),timer=setTimeout(abort,8000);signal?.addEventListener?.('abort',abort,{once:true});try{const response=await fetch(url,{headers:{Accept:'application/json'},signal:controller.signal,cache:'no-store'});if(!response.ok)throw new Error(`HTTP ${response.status}`);return await response.json()}finally{clearTimeout(timer);signal?.removeEventListener?.('abort',abort)}}
  async function fetchProduct(code,signal){const urls=[`${API_V2}${encodeURIComponent(code)}.json?fields=${encodeURIComponent(FIELDS)}`,`${API_V0}${encodeURIComponent(code)}.json`],results=await Promise.allSettled(urls.map(url=>requestJson(url,signal)));const payloads=results.filter(result=>result.status==='fulfilled').map(result=>result.value),v2=payloads.find(value=>value?.status===1&&value.product&&useful(nutrition(value.product))),fallback=payloads.find(value=>value?.status===1&&value.product);return(v2||fallback)?.product||null}
  function saveProduct(code,product,offValues){savePortionProfile(code,product);const db=window.CutCoachLibrary.exportData(),existing=db.items.find(item=>item.barcode===code),override=readOverrides()[code],{available,unit,...values}=offValues;let item,isExisting=Boolean(existing),usedOverride=false;if(existing&&override){item={...existing,source:'off',sourceId:code,sourceVersion:'2',modified:true};usedOverride=true}else{item={id:existing?.id||`off_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,8)}`,name:productName(product),kind:'food',barcode:code,amount:100,unit,...values,source:'off',sourceId:code,sourceVersion:'2',sourceLabel:'Open Food Facts · Produktdaten',modified:false,favorite:Boolean(existing?.favorite),uses:existing?.uses||0,lastUsedAt:existing?.lastUsedAt||null,createdAt:existing?.createdAt||new Date().toISOString(),components:[]};if(existing)Object.assign(existing,item);else db.items.push(item);window.CutCoachLibrary.importData(db)}return{item,isExisting,usedOverride}}
  function openManual(code,product=null,values=null){originalLookup?.();setTimeout(()=>{if(product){const name=$('#libName');if(name)name.value=productName(product);for(const[selector,value]of[['#libCalories',values?.calories],['#libProtein',values?.protein],['#libCarbs',values?.carbs],['#libFat',values?.fat],['#libFiber',values?.fiber],['#libSugar',values?.sugar],['#libSaturatedFat',values?.saturatedFat],['#libSalt',values?.salt]]){const input=$(selector);if(input&&Number.isFinite(value))input.value=value}const unit=$('#libUnit');if(unit&&values?.unit)unit.value=values.unit}const barcode=$('#libBarcode');if(barcode)barcode.value=code},120)}
  function ensureModal(){if($('#offResultModal'))return;const style=document.createElement('style');style.textContent='.off-result-card{display:grid;grid-template-columns:76px 1fr;gap:14px;align-items:center;padding:14px;border-radius:18px;background:#182238}.off-result-card.no-image{grid-template-columns:1fr}.off-result-card img{width:76px;height:76px;border-radius:14px;object-fit:contain;background:#fff}.off-result-card b,.off-result-card small{display:block}.off-result-card small{color:var(--muted);margin-top:5px}.off-result-actions{display:grid;gap:9px;margin-top:14px}.off-result-actions .secondary{width:100%}.off-result-source{text-align:center;color:var(--muted);font-size:11px;margin-top:10px}';document.head.append(style);document.body.insertAdjacentHTML('beforeend','<div class="modal" id="offResultModal" role="dialog" aria-modal="true" aria-hidden="true" aria-labelledby="offResultTitle"><div class="sheet"><div class="sheet-head"><h2 id="offResultTitle">Produkt gespeichert</h2><button id="offResultClose" type="button" aria-label="Schließen">×</button></div><div id="offResultCard"></div><div class="off-result-actions"><button id="offSaveOnly" type="button">✓ In Bibliothek lassen</button><button id="offEatNow" class="secondary" type="button">🍽️ Jetzt essen</button><button id="offEditNow" class="secondary" type="button">✏️ Bearbeiten</button></div><div class="off-result-source">Datenquelle: Open Food Facts · Basis 100 g/ml je Produkt</div></div></div>');$('#offResultClose').onclick=closeResult;$('#offSaveOnly').onclick=closeResult;$('#offEatNow').onclick=()=>openAction('use');$('#offEditNow').onclick=()=>openAction('edit');$('#offResultModal').addEventListener('click',event=>{if(event.target.id==='offResultModal')closeResult()})}
  function closeResult(){closeModal($('#offResultModal'));resultItemId=null}
  function openAction(action){const id=resultItemId;closeModal($('#offResultModal'));setTimeout(()=>{const esc=globalThis.CSS?.escape?CSS.escape(id):String(id).replace(/[^A-Za-z0-9_-]/g,''),button=document.querySelector(action==='edit'?`[data-edit-lib="${esc}"]`:`[data-use-lib="${esc}"]`);if(button)button.click();else toast('Produkt ist gespeichert. Öffne es über die Bibliothek.')},80)}
  function showResult(saved,product){resultItemId=saved.item.id;const values=saved.item,image=String(product.image_front_small_url||product.image_url||''),card=$('#offResultCard');card.className=`off-result-card${image?'':' no-image'}`;card.innerHTML=`${image?`<img src="${escapeHtml(image)}" alt="">`:''}<div><b>${escapeHtml(values.name)}</b><small>${values.calories} kcal · ${values.protein} g Eiweiß · ${values.carbs} g KH · ${values.fat} g Fett · je ${values.amount} ${values.unit}</small><small>${saved.usedOverride?'Deine lokal angepassten Werte wurden beibehalten.':saved.isExisting?'Open-Food-Facts-Werte wurden aktualisiert.':'Neu zur Bibliothek hinzugefügt.'}</small></div>`;$('#offResultTitle').textContent=saved.usedOverride?'Eigene Werte geschützt':saved.isExisting?'Produkt aktualisiert':'Produkt gespeichert';closeModal($('#scannerModal'));openModal('offResultModal')}
  async function lookup(){if(busy)return false;const code=cleanCode($('#manualCode')?.value);if(!code){toast('Bitte einen gültigen Barcode eingeben.');return false}if(navigator.onLine===false){toast('Offline: gespeicherte lokale Daten werden verwendet.');originalLookup?.();return false}busy=true;lookupController?.abort();lookupController=new AbortController();const button=$('#lookupManualCode');if(button){button.disabled=true;button.textContent='Suche …'}status('Produkt und Nährwerte werden bei Open Food Facts gesucht …');try{const product=await fetchProduct(code,lookupController.signal);if(!product){status('Produkt nicht bei Open Food Facts gefunden. Werte bitte einmalig eintragen.','error');openManual(code);return false}const values=nutrition(product);if(!values.available){status('Produkt gefunden, aber keine verwertbaren Energieangaben hinterlegt. Bitte Werte ergänzen.','error');openManual(code,product,values);return false}const saved=saveProduct(code,product,values);status(`Gefunden: ${saved.item.name} · ${saved.item.calories} kcal/${saved.item.amount} ${saved.item.unit}`,'success');showResult(saved,product);return true}catch(error){if(error?.name!=='AbortError'){console.warn('Open Food Facts lookup failed',error);toast('Open Food Facts ist gerade nicht erreichbar. Lokale Daten werden verwendet.');originalLookup?.()}return false}finally{busy=false;lookupController=null;if(button){button.disabled=false;button.textContent='Suchen'}}}
  function cancel(){lookupController?.abort();lookupController=null;busy=false;const button=$('#lookupManualCode');if(button){button.disabled=false;button.textContent='Suchen'}}
  function init(){const button=$('#lookupManualCode');if(!button||!window.CutCoachLibrary)return false;if(button.dataset.off181)return true;button.dataset.off181='1';originalLookup=button.onclick;button.onclick=lookup;ensureModal();return true}
  function bootstrap(){if(init())return;bootstrapObserver=new MutationObserver(()=>{if(init()){bootstrapObserver.disconnect();bootstrapObserver=null}});bootstrapObserver.observe(document.body||document.documentElement,{childList:true,subtree:true})}
  window.addEventListener('pagehide',cancel);window.addEventListener('offline',cancel);
  window.CutCoachOffLookup=Object.freeze({version:VERSION,lookup,cancel,nutrition,basisUnit,state:()=>Object.freeze({busy})});
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bootstrap,{once:true});else bootstrap();
})();
