'use strict';
(function(){
  const VERSION='4.2.0';
  const LIB='cutcoach_library_v1';
  const OVR='cutcoach_library_overrides_v1';
  const WATER='cutcoach_water_v1';
  const COMPLETE_PREVIOUS='cutcoach_previous_complete_v1';
  const readJson=(key,fallback)=>{try{const parsed=JSON.parse(localStorage.getItem(key)||'null');return parsed??fallback}catch{return fallback}};
  const library=()=>{try{return window.CutCoachLibrary?.exportData?.()||readJson(LIB,{version:1,items:[]})}catch{return{version:1,items:[]}}};
  const overrides=()=>{const value=readJson(OVR,{});return value&&typeof value==='object'&&!Array.isArray(value)?value:{}};
  const hydration=()=>{const value=readJson(WATER,{});return value&&typeof value==='object'&&!Array.isArray(value)?value:{}};
  const writeJson=(key,value)=>{try{localStorage.setItem(key,JSON.stringify(value));return true}catch{return false}};
  function completeSnapshot(reason){return{reason,savedAt:new Date().toISOString(),appVersion:VERSION,state:deepClone(state),library:library(),libraryOverrides:overrides(),hydration:hydration()}}
  function saveCompletePrevious(reason){return writeJson(COMPLETE_PREVIOUS,completeSnapshot(reason))}
  function restoreParts(payload){state=sanitizeState(payload.state||payload.data,{rejectFuture:true});startupWarning=null;storageReadOnly=false;lastSavedSnapshot='';selectedDate=todayKey();saveState(true);if(payload.library)window.CutCoachLibrary?.importData?.(payload.library);if(payload.libraryOverrides&&typeof payload.libraryOverrides==='object')writeJson(OVR,payload.libraryOverrides);else localStorage.removeItem(OVR);if(payload.hydration&&typeof payload.hydration==='object')writeJson(WATER,payload.hydration);else localStorage.removeItem(WATER);render();window.CutCoachLibrary?.render?.()}
  async function exportAll(event){event.preventDefault();event.stopImmediatePropagation();const at=new Date().toISOString(),copy=deepClone(state);copy.meta.lastBackupAt=at;copy.meta.appVersion=VERSION;const envelope={format:'cutcoach-backup',formatVersion:4,appVersion:VERSION,schemaVersion:SCHEMA_VERSION,exportedAt:at,data:copy,library:library(),libraryOverrides:overrides(),hydration:hydration()};try{await shareOrDownload(JSON.stringify(envelope,null,2),`CutCoach-Komplettbackup-${todayKey()}.json`,'CutCoach Komplettbackup');state.meta.lastBackupAt=at;saveState(true);render();toast('Komplettbackup inklusive Bibliothek und Wasser erstellt.')}catch(error){if(error?.name!=='AbortError')toast('Backup konnte nicht exportiert werden.')}}
  function importAll(event){event.stopImmediatePropagation();const file=event.target.files?.[0];event.target.value='';if(!file)return;if(file.size>10*1024*1024){toast('Das Backup ist zu groß.');return}const reader=new FileReader();reader.onload=()=>{try{const parsed=JSON.parse(reader.result),raw=parsed?.format==='cutcoach-backup'?parsed.data:parsed;if(!raw?.settings||!raw?.days)throw new Error('invalid');if(Number(parsed?.schemaVersion||schemaVersionOf(raw))>SCHEMA_VERSION)throw new Error('future-schema');const clean=sanitizeState(raw,{rejectFuture:true}),days=Object.keys(clean.days).length,meals=Object.values(clean.days).reduce((sum,item)=>sum+item.meals.length,0),count=Array.isArray(parsed?.library?.items)?parsed.library.items.length:0;if(!confirm(`Backup mit ${days} Tagen, ${meals} Mahlzeiten und ${count} Bibliothekseinträgen importieren? Der aktuelle Gesamtstand wird vorher lokal gesichert.`))return;saveCompletePrevious('Vor Komplettbackup-Import');restoreParts({state:clean,library:parsed.library,libraryOverrides:parsed.libraryOverrides,hydration:parsed.hydration});toast('Komplettbackup importiert.')}catch(error){toast(error?.message==='future-schema'?'Backup stammt aus einer neueren Version.':'Ungültiges oder beschädigtes Backup.')}};reader.onerror=()=>toast('Backup konnte nicht gelesen werden.');reader.readAsText(file)}
  function restoreComplete(event){const raw=localStorage.getItem(COMPLETE_PREVIOUS);if(!raw)return;event.preventDefault();event.stopImmediatePropagation();try{const payload=JSON.parse(raw),stamp=payload.savedAt?new Date(payload.savedAt).toLocaleString('de-DE'):'unbekannt';if(!confirm(`Gesamtstand „${payload.reason||'Vorheriger Stand'}“ vom ${stamp} wiederherstellen?`))return;const current=completeSnapshot('Vor Wiederherstellung');restoreParts(payload);writeJson(COMPLETE_PREVIOUS,current);toast('Vorheriger Gesamtstand wiederhergestellt.')}catch{toast('Der vorherige Gesamtstand ist beschädigt.')}}
  function resetAll(event){event.preventDefault();event.stopImmediatePropagation();if(!confirm('Wirklich alle CutCoach-Daten inklusive Lebensmittelbibliothek und Wasser löschen? Der aktuelle Gesamtstand wird vorher lokal gesichert.'))return;saveCompletePrevious('Vor vollständigem Zurücksetzen');removeStorage(STORAGE_KEY);removeStorage(RECOVERY_KEY);localStorage.removeItem(LIB);localStorage.removeItem(OVR);localStorage.removeItem(WATER);window.CutCoachLibrary?.importData?.({version:1,items:[]});storageReadOnly=false;startupWarning=null;state=sanitizeState(DEFAULTS);lastSavedSnapshot='';selectedDate=todayKey();saveState(true);render();openModal('onboardingModal');toast('Alle Daten wurden zurückgesetzt.')}
  function recordOverride(){const barcode=document.querySelector('#libBarcode')?.value?.trim();if(!barcode)return;setTimeout(()=>{const item=library().items.find(entry=>entry.barcode===barcode);if(!item)return;const map=overrides();map[barcode]={editedAt:new Date().toISOString(),name:item.name,amount:item.amount,unit:item.unit,calories:item.calories,protein:item.protein,carbs:item.carbs,fat:item.fat};writeJson(OVR,map)},120)}
  function cleanupDeletedOverride(){const barcode=document.querySelector('#libBarcode')?.value?.trim();if(!barcode)return;setTimeout(()=>{const exists=library().items.some(item=>item.barcode===barcode);if(!exists){const map=overrides();delete map[barcode];writeJson(OVR,map)}},120)}
  function exactAmount(){const factor=document.querySelector('#libraryFactor');if(!factor||document.querySelector('#libraryExactAmount'))return;const label=document.createElement('label');label.innerHTML='Exakte Menge <div class="inline exact-amount"><input id="libraryExactAmount" type="number" inputmode="decimal" min="0.1" max="10000" step="0.1" placeholder="z. B. 25"><span id="libraryExactUnit">g</span></div>';factor.closest('label')?.after(label);const input=label.querySelector('input'),unit=label.querySelector('span');function syncFromModal(){const text=document.querySelector('#libraryUseSummary small')?.textContent||'',match=text.match(/Basis:\s*([\d.,]+)\s*(g|ml|Stück|Portion)/i);if(!match)return;input.value=match[1].replace(',','.');unit.textContent=match[2];factor.querySelector('[data-custom]')?.remove();factor.value='1';factor.dispatchEvent(new Event('change',{bubbles:true}))}input.addEventListener('input',()=>{const text=document.querySelector('#libraryUseSummary small')?.textContent||'',match=text.match(/Basis:\s*([\d.,]+)\s*(g|ml|Stück|Portion)/i);if(!match)return;const base=Number(match[1].replace(',','.')),amount=Number(String(input.value).replace(',','.'));unit.textContent=match[2];if(!(base>0&&amount>0))return;let option=factor.querySelector('[data-custom]');if(!option){option=document.createElement('option');option.dataset.custom='1';factor.append(option)}option.value=String(amount/base);option.textContent=`${String(amount).replace('.',',')} ${match[2]}`;factor.value=option.value;factor.dispatchEvent(new Event('change',{bubbles:true}))});new MutationObserver(()=>{if(document.querySelector('#libraryUseModal')?.classList.contains('open'))syncFromModal()}).observe(document.querySelector('#libraryUseModal'),{attributes:true,attributeFilter:['class']})}
  function libraryHashFix(){window.addEventListener('hashchange',()=>{if(location.hash==='#library')document.querySelector('[data-tab="library"]')?.click()});if(location.hash==='#library')setTimeout(()=>document.querySelector('[data-tab="library"]')?.click(),0)}
  function libraryCrossTab(){window.addEventListener('storage',event=>{if(event.key===LIB&&event.newValue){try{const current=JSON.stringify(library());if(current!==event.newValue){window.CutCoachLibrary?.importData?.(JSON.parse(event.newValue));toast('Bibliothek aus einem anderen Fenster aktualisiert.')}}catch{}}if(event.key===OVR&&event.newValue===null)toast('Lokale Produktanpassungen wurden entfernt.');if(event.key===WATER)render()})}
  function init(){const version=document.querySelector('#appVersion');if(version)version.textContent=`Version ${VERSION}`;document.querySelector('#exportData')?.addEventListener('click',exportAll,true);document.querySelector('#importData')?.addEventListener('change',importAll,true);document.querySelector('#restorePrevious')?.addEventListener('click',restoreComplete,true);document.querySelector('#resetData')?.addEventListener('click',resetAll,true);document.querySelector('#saveLibraryItem')?.addEventListener('click',recordOverride,true);document.querySelector('#deleteLibraryItem')?.addEventListener('click',cleanupDeletedOverride,true);const restore=document.querySelector('#restorePrevious');if(restore&&localStorage.getItem(COMPLETE_PREVIOUS))restore.hidden=false;exactAmount();libraryHashFix();libraryCrossTab()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,250),{once:true});else setTimeout(init,250);
})();