'use strict';
(function(){
const VERSION='3.4.0',LIB='cutcoach_library_v1',OVR='cutcoach_library_overrides_v1';
const lib=()=>{try{return window.CutCoachLibrary?.exportData?.()||JSON.parse(localStorage.getItem(LIB)||'{"version":1,"items":[]}')}catch{return{version:1,items:[]}}};
const getO=()=>{try{return JSON.parse(localStorage.getItem(OVR)||'{}')}catch{return{}}};
const setO=v=>{try{localStorage.setItem(OVR,JSON.stringify(v))}catch{}};
async function exportAll(e){e.preventDefault();e.stopImmediatePropagation();const at=new Date().toISOString(),copy=deepClone(state);copy.meta.lastBackupAt=at;copy.meta.appVersion=VERSION;const env={format:'cutcoach-backup',formatVersion:2,appVersion:VERSION,schemaVersion:SCHEMA_VERSION,exportedAt:at,data:copy,library:lib(),libraryOverrides:getO()};try{await shareOrDownload(JSON.stringify(env,null,2),`CutCoach-Komplettbackup-${todayKey()}.json`,'CutCoach Komplettbackup');state.meta.lastBackupAt=at;saveState(true);render();toast('Komplettbackup inklusive Bibliothek erstellt.')}catch(x){if(x?.name!=='AbortError')toast('Backup konnte nicht exportiert werden.')}}
function importAll(e){e.stopImmediatePropagation();const file=e.target.files?.[0];e.target.value='';if(!file)return;if(file.size>8*1024*1024){toast('Das Backup ist zu groß.');return}const r=new FileReader();r.onload=()=>{try{const p=JSON.parse(r.result),raw=p?.format==='cutcoach-backup'?p.data:p;if(!raw?.settings||!raw?.days)throw Error('invalid');if(Number(p?.schemaVersion||schemaVersionOf(raw))>SCHEMA_VERSION)throw Error('future-schema');const clean=sanitizeState(raw,{rejectFuture:true}),days=Object.keys(clean.days).length,meals=Object.values(clean.days).reduce((s,d)=>s+d.meals.length,0),lc=Array.isArray(p?.library?.items)?p.library.items.length:0;if(!confirm(`Backup mit ${days} Tagen, ${meals} Mahlzeiten und ${lc} Bibliothekseinträgen importieren?`))return;savePreviousState('Vor Komplettbackup-Import');state=clean;startupWarning=null;storageReadOnly=false;lastSavedSnapshot='';selectedDate=todayKey();saveState(true);if(p.library)window.CutCoachLibrary?.importData?.(p.library);if(p.libraryOverrides&&typeof p.libraryOverrides==='object')setO(p.libraryOverrides);render();toast('Komplettbackup importiert.')}catch(x){toast(x?.message==='future-schema'?'Backup stammt aus einer neueren Version.':'Ungültiges oder beschädigtes Backup.')}};r.onerror=()=>toast('Backup konnte nicht gelesen werden.');r.readAsText(file)}
function exactAmount(){const f=document.querySelector('#libraryFactor');if(!f||document.querySelector('#libraryExactAmount'))return;const l=document.createElement('label');l.innerHTML='Exakte Menge <div class="inline exact-amount"><input id="libraryExactAmount" type="number" inputmode="decimal" min="0.1" max="10000" step="0.1" placeholder="z. B. 25"><span id="libraryExactUnit">g</span></div>';f.closest('label')?.after(l);const i=l.querySelector('input');i.oninput=()=>{const t=document.querySelector('#libraryUseSummary small')?.textContent||'',m=t.match(/Basis:\s*([\d.,]+)\s*(g|ml|Stück|Portion)/i);if(!m)return;const base=Number(m[1].replace(',','.')),a=Number(String(i.value).replace(',','.'));document.querySelector('#libraryExactUnit').textContent=m[2];if(!(base>0&&a>0))return;let o=f.querySelector('[data-custom]');if(!o){o=document.createElement('option');o.dataset.custom='1';f.append(o)}o.value=String(a/base);o.textContent=`${String(a).replace('.',',')} ${m[2]}`;f.value=o.value;f.dispatchEvent(new Event('change',{bubbles:true}))};new MutationObserver(()=>{const modal=document.querySelector('#libraryUseModal');if(!modal?.classList.contains('open'))return;const t=document.querySelector('#libraryUseSummary small')?.textContent||'',m=t.match(/Basis:\s*([\d.,]+)\s*(g|ml|Stück|Portion)/i);if(m){i.value=m[1].replace(',','.');document.querySelector('#libraryExactUnit').textContent=m[2]}}).observe(document.querySelector('#libraryUseModal'),{attributes:true,attributeFilter:['class']})}
function markOverride(){const b=document.querySelector('#libBarcode')?.value?.trim();if(!b)return;setTimeout(()=>{const o=getO();o[b]={editedAt:new Date().toISOString()};setO(o)},0)}
function resetAll(e){e.preventDefault();e.stopImmediatePropagation();if(!confirm('Wirklich alle CutCoach-Daten inklusive Lebensmittelbibliothek löschen?'))return;savePreviousState('Vor vollständigem Zurücksetzen');removeStorage(STORAGE_KEY);removeStorage(RECOVERY_KEY);localStorage.removeItem(LIB);localStorage.removeItem(OVR);window.CutCoachLibrary?.importData?.({version:1,items:[]});storageReadOnly=false;startupWarning=null;state=sanitizeState(DEFAULTS);lastSavedSnapshot='';selectedDate=todayKey();saveState(true);render();openModal('onboardingModal');toast('Alle Daten wurden zurückgesetzt.')}
function init(){const v=document.querySelector('#appVersion');if(v)v.textContent=`Version ${VERSION}`;document.querySelector('#exportData')?.addEventListener('click',exportAll,true);document.querySelector('#importData')?.addEventListener('change',importAll,true);document.querySelector('#resetData')?.addEventListener('click',resetAll,true);document.querySelector('#saveLibraryItem')?.addEventListener('click',markOverride,true);exactAmount()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,250),{once:true});else setTimeout(init,250)
})();