'use strict';
(function(){
  const RELEASE='1.2.2 Alpha';
  window.CUTCOACH_RELEASE=RELEASE;
  const escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
  const normalized=value=>String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('de').replace(/ß/g,'ss').replace(/[^a-z0-9]+/g,' ').trim().replace(/\s+/g,' ');
  const compact=value=>normalized(value).replace(/\s+/g,'');
  const fmt=(value,digits=0)=>new Intl.NumberFormat('de-DE',{minimumFractionDigits:digits,maximumFractionDigits:digits}).format(Math.max(0,Number(value)||0));
  function editDistanceWithin(left,right,limit){if(left===right)return 0;if(Math.abs(left.length-right.length)>limit)return limit+1;let previous=Array.from({length:right.length+1},(_,index)=>index);for(let row=1;row<=left.length;row++){const current=[row];let best=current[0];for(let column=1;column<=right.length;column++){const value=Math.min(current[column-1]+1,previous[column]+1,previous[column-1]+Number(left[row-1]!==right[column-1]));current[column]=value;best=Math.min(best,value)}if(best>limit)return limit+1;previous=current}return previous[right.length]}
  function recipeSearchScore(item,query){const name=normalized(item.name),aliases=(Array.isArray(item.aliases)?item.aliases:[item.aliases]).filter(Boolean).map(normalized),search=[name,...aliases].join(' '),nameCompact=compact(item.name),searchCompact=compact(search),queryNormalized=normalized(query),queryCompact=compact(query),tokens=queryNormalized.split(/\s+/).filter(Boolean),limit=queryCompact.length>=9?2:1;const compactHit=searchCompact.includes(queryCompact)||queryCompact.includes(nameCompact),tokenHit=tokens.every(token=>search.includes(token)||searchCompact.includes(compact(token))),fuzzy=queryCompact.length>=4&&editDistanceWithin(queryCompact,nameCompact,limit)<=limit;if(!compactHit&&!tokenHit&&!fuzzy)return null;let score=0;if(nameCompact===queryCompact)score+=1200;else if(aliases.some(alias=>compact(alias)===queryCompact))score+=1050;else if(nameCompact.startsWith(queryCompact))score+=700;else if(compactHit)score+=400;if(tokenHit)score+=220;if(fuzzy)score+=60;return score+Number(Boolean(item.favorite))*80+Math.min(100,Number(item.uses)||0)}
  function enhanceRecipeSearch(input){const host=document.querySelector('#recipeV7SearchResults'),query=String(input.value||'').trim();if(!host||!query)return;let personal=[];try{personal=window.CutCoachLibrary?.exportData?.().items?.filter(item=>item.kind==='food')||[]}catch{}let catalog=[];try{catalog=window.CutCoachFoodCatalog?.items?.()||[]}catch{}const seen=new Set(),ranked=[];for(const item of [...personal,...catalog]){const key=String(item.id);if(seen.has(key))continue;seen.add(key);const score=recipeSearchScore(item,query);if(score!==null)ranked.push({item,score})}const items=ranked.sort((a,b)=>b.score-a.score||String(a.item.name).localeCompare(String(b.item.name),'de')).slice(0,24).map(entry=>entry.item);if(!items.length)return;host.innerHTML=items.map(item=>`<button type="button" data-recipe-ingredient="${escapeHtml(item.id)}"><span>${item.source==='bls'?'BLS':item.source==='off'?'Produkt':item.source==='cutcoach'?'Standard':'Eigene'}</span><b>${escapeHtml(item.name)}</b><small>${fmt(item.calories)} kcal · ${fmt(item.protein,1)} g E · Basis ${fmt(item.amount,item.amount%1?1:0)} ${escapeHtml(item.unit||'g')}</small></button>`).join('')}
  function setVersion(){const node=document.querySelector('#appVersion'),text=`Version ${RELEASE}`;if(node&&node.textContent!==text)node.textContent=text;return node}
  function addStyle(key,href){if(document.querySelector(`link[data-${key}]`))return;const link=document.createElement('link');link.rel='stylesheet';link.href=href;link.dataset[key.replace(/-([a-z])/g,(_,char)=>char.toUpperCase())]='1';document.head.append(link)}
  function addScript(key,src,onload){if(document.querySelector(`script[data-${key}]`))return;const script=document.createElement('script');script.src=src;script.async=false;script.dataset[key.replace(/-([a-z])/g,(_,char)=>char.toUpperCase())]='1';if(onload)script.onload=onload;document.head.append(script)}
  function loadJournal72(){addStyle('journal-v72','./journal-v72.css?v=7.2.0');addStyle('ui-cleanup-v732','./ui-cleanup-v732.css?v=7.3.3');addStyle('journal-smart-v740','./journal-smart-v740.css?v=1.0.0-alpha');const loadSmart=()=>{if(!window.CutCoachJournalV740)addScript('journal-smart-v740','./journal-smart-v740.js?v=1.0.0-alpha')};if(window.CutCoachJournalV72){loadSmart();return}if(document.querySelector('script[data-journal-v72]')){setTimeout(loadSmart,120);return}addScript('journal-v72','./journal-v72.js?v=7.2.0',loadSmart)}
  function loadJournalEnergy143(){if(!window.CutCoachJournalEnergyLive143)addScript('journal-energy-live-v143','./journal-energy-live-v143.js?v=1.4.3-alpha')}
  function loadNutrition110(){addStyle('nutrition-v110','./nutrition-v110.css?v=1.1.2-alpha');if(!window.CutCoachNutritionV110)addScript('nutrition-v110','./nutrition-v110.js?v=1.1.2-alpha')}
  function loadNutritionVoice111(){addStyle('nutrition-voice-111','./nutrition-voice-111.css?v=1.1.2-alpha');if(!window.CutCoachNutritionVoice111)addScript('nutrition-voice-111','./nutrition-voice-111.js?v=1.9.0-alpha')}
  function loadNutritionMulti120(){
    addStyle('nutrition-multisearch-120','./nutrition-multisearch-120.css?v=1.2.3-alpha');addStyle('nutrition-search-confidence-v150','./nutrition-search-confidence-v150.css?v=1.7.1-alpha');
    const ensure=(key,src,ready,next)=>{if(ready()){next();return}let completed=false,timeout=0;const finish=()=>{if(completed)return;completed=true;clearTimeout(timeout);next()};timeout=setTimeout(finish,4500);let existing=document.querySelector(`script[data-${key}]`);if(existing){const previousLoad=existing.onload,previousError=existing.onerror;existing.onload=event=>{previousLoad?.call(existing,event);finish()};existing.onerror=event=>{previousError?.call(existing,event);finish()};queueMicrotask(()=>{if(ready())finish()});return}existing=document.createElement('script');existing.src=src;existing.async=false;existing.dataset[key.replace(/-([a-z])/g,(_,char)=>char.toUpperCase())]='1';existing.onload=finish;existing.onerror=finish;(document.head||document.documentElement).append(existing)};
    const loadCompatibility=()=>{if(!window.CutCoachNutritionMultiSearch120)addScript('nutrition-multisearch-120','./nutrition-multisearch-120.js?v=1.9.6-compat')};
    const attachLayers=()=>{let engine=window.CutCoachIntelligentSearch128;engine=window.CutCoachSearchExactWhole170?.attach?.(engine)||engine;engine=window.CutCoachSearchConfidenceHardening151?.attach?.(engine)||engine;engine=window.CutCoachPortionHardening153?.attach?.(engine)||engine;window.CutCoachSearchLearning161?.installLibraryHook?.();loadCompatibility()};
    const loadCanonical=()=>ensure('nutrition-intelligent-search-128','./nutrition-multisearch-canonical-128.js?v=1.5.0-alpha',()=>Boolean(window.CutCoachIntelligentSearch128),attachLayers);
    const loadConfidence=()=>ensure('nutrition-search-confidence-hardening-v151','./nutrition-search-confidence-hardening-v151.js?v=1.9.0-alpha',()=>Boolean(window.CutCoachSearchConfidenceHardening151),loadCanonical);
    const loadExactWhole=()=>ensure('nutrition-search-exact-whole-v170','./nutrition-search-exact-whole-v170.js?v=1.9.6-alpha',()=>Boolean(window.CutCoachSearchExactWhole170),loadConfidence);
    const loadLearning=()=>ensure('nutrition-search-learning-v161','./nutrition-search-learning-v161.js?v=1.6.1-alpha',()=>Boolean(window.CutCoachSearchLearning161),loadExactWhole);
    const loadPortionHardening=()=>ensure('nutrition-portion-hardening-v153','./nutrition-portion-hardening-v153.js?v=1.9.0-alpha',()=>Boolean(window.CutCoachPortionHardening153),loadLearning);
    ensure('nutrition-portion-profiles-v153','./nutrition-portion-profiles-v153.js?v=1.5.3-alpha',()=>Boolean(window.CutCoachPortionProfiles153),loadPortionHardening);
  }
  function loadNutritionStage6(){addStyle('nutrition-production-acceptance-v180','./nutrition-production-acceptance-v180.css?v=1.8.0-alpha');if(!window.CutCoachNutritionStage6)addScript('nutrition-production-acceptance-v180','./nutrition-production-acceptance-v180.js?v=1.8.0-alpha')}
  function loadNutrition73(){addStyle('nutrition-v73','./nutrition-v73.css?v=7.3.1');if(window.CutCoachNutritionV73||document.querySelector('script[data-nutrition-v73]')){loadNutrition110();loadNutritionVoice111();loadNutritionMulti120();return}addScript('nutrition-v73','./nutrition-v73.js?v=7.3.2',()=>{loadNutrition110();loadNutritionVoice111();loadNutritionMulti120()})}
  function loadNutritionCleanup(){addStyle('nutrition-cleanup-101','./nutrition-cleanup-101.css?v=1.0.3-alpha');if(!window.CutCoachNutritionCleanup101)addScript('nutrition-cleanup-101','./nutrition-cleanup-101.js?v=1.0.3-alpha')}
  function loadCatalogExpansion191(){if(window.CutCoachCatalogExpansion191){loadNutrition73();return}if(document.querySelector('script[data-catalog-expansion-v191]')){setTimeout(loadCatalogExpansion191,100);return}addScript('catalog-expansion-v191','./catalog-expansion-v191.js?v=1.9.1-alpha',loadNutrition73)}
  function loadLocalDishes140(){if(window.CutCoachLocalDishes140){loadCatalogExpansion191();return}if(document.querySelector('script[data-local-dishes-v140]')){setTimeout(loadLocalDishes140,100);return}addScript('local-dishes-v140','./local-dishes-v140.js?v=1.4.0-alpha',loadCatalogExpansion191)}
  function loadCatalog73(){if(window.CutCoachEverydayCatalog){loadLocalDishes140();return}if(document.querySelector('script[data-everyday-v73]'))return;addScript('everyday-v73','./everyday-catalog-v73.js?v=7.3.0',loadLocalDishes140)}
  function loadGlassNavigation(){const load=()=>{if(!window.CutCoachGlassNavV131)addScript('glass-nav-v131','./glass-nav-v131.js?v=1.3.2-alpha')};let link=document.querySelector('link[data-glass-nav-v131]');if(link){if(link.sheet)load();else{link.addEventListener('load',load,{once:true});link.addEventListener('error',load,{once:true})}return}link=document.createElement('link');link.rel='stylesheet';link.href='./glass-nav-v131.css?v=1.3.6-alpha';link.dataset.glassNavV131='1';link.addEventListener('load',load,{once:true});link.addEventListener('error',load,{once:true});document.head.append(link)}
  function loadJournalPolish137(){addStyle('journal-polish-v137','./journal-polish-v137.css?v=1.3.7-alpha');if(!window.CutCoachJournalPolish137)addScript('journal-polish-v137','./journal-polish-v137.js?v=1.3.7-alpha')}
  function loadNutritionPolish138(){addStyle('nutrition-polish-v138','./nutrition-polish-v138.css?v=1.3.8-alpha');const loadPolish=()=>{if(!window.CutCoachNutritionPolish138)addScript('nutrition-polish-v138','./nutrition-polish-v138.js?v=1.3.11-alpha')};if(window.CutCoachSearchInputPerformance193){loadPolish();return}let script=document.querySelector('script[data-nutrition-search-input-performance-v193]');if(script){script.addEventListener('load',loadPolish,{once:true});script.addEventListener('error',loadPolish,{once:true});setTimeout(loadPolish,220);return}script=document.createElement('script');script.src='./nutrition-search-input-performance-v193.js?v=1.9.7-alpha';script.async=false;script.dataset.nutritionSearchInputPerformanceV193='1';script.onload=loadPolish;script.onerror=loadPolish;document.head.append(script)}
  async function exportBackupV7(event){const button=event.target.closest?.('#exportData');if(!button)return;event.preventDefault();event.stopImmediatePropagation();try{const envelope=typeof backupEnvelope==='function'?backupEnvelope():{format:'cutcoach-backup',formatVersion:1,schemaVersion:typeof SCHEMA_VERSION==='number'?SCHEMA_VERSION:null,exportedAt:new Date().toISOString(),data:typeof state==='object'?JSON.parse(JSON.stringify(state)):null};envelope.appVersion=RELEASE;if(envelope.data?.meta)envelope.data.meta.appVersion=RELEASE;await shareOrDownload(JSON.stringify(envelope,null,2),`CutCoach-Backup-${typeof todayKey==='function'?todayKey():new Date().toISOString().slice(0,10)}.json`);if(typeof commitStateMutation==='function')commitStateMutation(current=>{current.meta.lastBackupAt=envelope.exportedAt;current.meta.appVersion=RELEASE});window.render?.();toast?.('Backup erstellt.')}catch(error){if(error?.name!=='AbortError')toast?.('Backup konnte nicht exportiert werden.')}}
  let recipeTimer=0,recipeToken=0;
  document.addEventListener('input',event=>{if(event.target?.id!=='recipeV7Search')return;const input=event.target,token=++recipeToken;clearTimeout(recipeTimer);if(!event.isTrusted){queueMicrotask(()=>{if(token===recipeToken&&input.isConnected)enhanceRecipeSearch(input)});return}recipeTimer=setTimeout(()=>{if(token===recipeToken&&input.isConnected)enhanceRecipeSearch(input)},220)});
  document.addEventListener('click',exportBackupV7,true);
  const baseRender=window.render;if(typeof baseRender==='function')window.render=function(){baseRender();setVersion()};
  function watchVersionNode(){const existing=setVersion();if(existing){const observer=new MutationObserver(setVersion);observer.observe(existing,{childList:true,characterData:true,subtree:true});return}const bootstrap=new MutationObserver(()=>{const node=setVersion();if(!node)return;bootstrap.disconnect();const observer=new MutationObserver(setVersion);observer.observe(node,{childList:true,characterData:true,subtree:true})});bootstrap.observe(document.body||document.documentElement,{childList:true,subtree:true})}
  setVersion();const start=()=>{loadJournal72();loadJournalEnergy143();loadCatalog73();loadNutritionCleanup();loadNutrition110();loadNutritionVoice111();loadNutritionMulti120();loadGlassNavigation();loadJournalPolish137();loadNutritionPolish138();loadNutritionStage6();watchVersionNode()};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
