'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const project=path.resolve(__dirname,'..');
const js=fs.readFileSync(path.join(project,'nutrition-cleanup-101.js'),'utf8');
const css=fs.readFileSync(path.join(project,'nutrition-cleanup-101.css'),'utf8');
const version=fs.readFileSync(path.join(project,'version-v7.js'),'utf8');
const manifest=fs.readFileSync(path.join(project,'runtime-manifest.js'),'utf8');
const sw=fs.readFileSync(path.join(project,'sw.js'),'utf8');
const update=fs.readFileSync(path.join(project,'update.html'),'utf8');
assert.match(js,/nutrition-coach-row/,'Redundanter Ernährungshinweis wird nicht entfernt');
assert.match(js,/nutritionV7AnalysisText/,'Zusatzwert-Hinweis wird nicht entfernt');
assert.match(js,/Kohlenhydrate/,'KH wird nicht ausgeschrieben');
assert.match(js,/ensureAnalysisShell/,'Fehlende Zusatzwerte-Kopfzeile wird nicht wiederhergestellt');
assert.match(js,/nutrition-v7-analysis-toggle/,'Schalter für Zusatzwerte fehlt');
assert.match(js,/aria-expanded/,'Schalterzustand ist nicht zugänglich');
assert.match(css,/nutrition-v7-analysis-head\{display:flex!important/,'Kopfzeile wird nicht zuverlässig angezeigt');
assert.match(css,/nutrition-v7-analysis-toggle\{display:grid!important/,'Schalter wird nicht zuverlässig angezeigt');
assert.match(version,/const RELEASE='1\.0\.2 Alpha'/,'Sichtbare Version ist nicht 1.0.2 Alpha');
assert.match(version,/nutrition-cleanup-101\.js\?v=1\.0\.2-alpha/,'Cleanup-JavaScript wird nicht aktuell geladen');
assert.match(manifest,/version:'1\.0\.2-alpha'/,'Cacheversion ist nicht 1.0.2 Alpha');
assert.match(manifest,/nutrition-cleanup-101\.css\?v=1\.0\.2-alpha/,'Cleanup-CSS fehlt im Cache');
assert.match(sw,/runtime-manifest\.js\?v=1\.0\.2-alpha/,'Service Worker lädt falsches Manifest');
assert.match(update,/sw\.js\?v=1\.0\.2-alpha-force/,'Update-Seite installiert nicht 1.0.2 Alpha');
console.log('CutCoach 1.0.2 Alpha nutrition toggle test: ok');