'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const project=path.resolve(__dirname,'..');
const js=fs.readFileSync(path.join(project,'nutrition-v110.js'),'utf8');
const css=fs.readFileSync(path.join(project,'nutrition-v110.css'),'utf8');
const version=fs.readFileSync(path.join(project,'version-v7.js'),'utf8');
const manifest=fs.readFileSync(path.join(project,'runtime-manifest.js'),'utf8');
const sw=fs.readFileSync(path.join(project,'sw.js'),'utf8');
const update=fs.readFileSync(path.join(project,'update.html'),'utf8');
assert.match(js,/requestAnimationFrame/,'UI-Aktualisierungen werden nicht gebündelt');
assert.match(js,/IntersectionObserver/,'Ergebnislisten werden nicht progressiv aktiviert');
assert.match(js,/nutrition-result-add/,'Doppeltipp-Schutz fehlt');
assert.match(js,/root\.addEventListener/,'Listener sind nicht auf den Ernährungsbereich begrenzt');
assert.doesNotMatch(js,/observe\(document\.documentElement/,'Globale Dauerbeobachtung wurde wieder eingeführt');
assert.match(css,/content-visibility:auto/,'Ergebnislisten sind nicht für Rendering-Performance optimiert');
assert.match(css,/contain-intrinsic-size/,'Platzhaltergröße für virtuelle Darstellung fehlt');
assert.match(css,/prefers-reduced-motion/,'Bewegungsreduktion fehlt');
assert.match(version,/const RELEASE='1\.1\.1 Alpha'/,'Releaseversion ist nicht 1.1.1 Alpha');
assert.match(version,/nutrition-v110\.js\?v=1\.1\.0-alpha/,'Nutrition-Performance-Modul wird nicht geladen');
assert.match(manifest,/version:'1\.1\.1-alpha'/,'Cacheversion ist nicht 1.1.1 Alpha');
assert.match(manifest,/nutrition-v110\.css\?v=1\.1\.0-alpha/,'Nutrition-CSS fehlt im Cache');
assert.match(manifest,/nutrition-v110\.js\?v=1\.1\.0-alpha/,'Nutrition-JavaScript fehlt im Cache');
assert.match(sw,/runtime-manifest\.js\?v=1\.1\.1-alpha/,'Service Worker lädt falsches Manifest');
assert.match(update,/sw\.js\?v=1\.1\.1-alpha-force/,'Installer lädt falschen Service Worker');
console.log('CutCoach 1.1.1 Alpha nutrition performance test: ok');