'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const project=path.resolve(__dirname,'..');
const js=fs.readFileSync(path.join(project,'nutrition-v110.js'),'utf8');
const css=fs.readFileSync(path.join(project,'nutrition-v110.css'),'utf8');
const version=fs.readFileSync(path.join(project,'version-v7.js'),'utf8');
const manifest=fs.readFileSync(path.join(project,'runtime-manifest.js'),'utf8');
const sw=fs.readFileSync(path.join(project,'sw.js'),'utf8');
const update=fs.readFileSync(path.join(project,'update.html'),'utf8');
assert.ok(js.includes('requestAnimationFrame'));
assert.ok(js.includes('IntersectionObserver'));
assert.ok(js.includes('nutrition-result-add'));
assert.ok(js.includes('root.addEventListener'));
assert.ok(!js.includes('observe(document.documentElement'));
assert.ok(css.includes('content-visibility:auto'));
assert.ok(css.includes('contain-intrinsic-size'));
assert.ok(css.includes('prefers-reduced-motion'));
assert.ok(version.includes("const RELEASE='1.2.0 Alpha'"));
assert.ok(version.includes('nutrition-v110.js?v=1.1.0-alpha'));
assert.ok(manifest.includes("version:'1.2.0-alpha'"));
assert.ok(manifest.includes('nutrition-v110.css?v=1.1.0-alpha'));
assert.ok(manifest.includes('nutrition-v110.js?v=1.1.0-alpha'));
assert.ok(sw.includes('runtime-manifest.js?v=1.2.0-alpha'));
assert.ok(update.includes('sw.js?v=1.2.0-alpha-force'));
console.log('CutCoach 1.2.0 Alpha nutrition performance test: ok');