'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const project=path.resolve(__dirname,'..');
const js=fs.readFileSync(path.join(project,'nutrition-voice-111.js'),'utf8');
const css=fs.readFileSync(path.join(project,'nutrition-voice-111.css'),'utf8');
const version=fs.readFileSync(path.join(project,'version-v7.js'),'utf8');
const manifest=fs.readFileSync(path.join(project,'runtime-manifest.js'),'utf8');
const sw=fs.readFileSync(path.join(project,'sw.js'),'utf8');
const update=fs.readFileSync(path.join(project,'update.html'),'utf8');
assert.match(js,/SpeechRecognition\|\|window\.webkitSpeechRecognition/,'SpeechRecognition-Fallback fehlt');
assert.match(js,/stopImmediatePropagation/,'Alte Mikrofonlogik wird nicht zuverlässig abgefangen');
assert.match(js,/aria-pressed/,'Aufnahmestatus ist nicht zugänglich');
assert.match(js,/12000/,'Sicherheits-Timeout für die Aufnahme fehlt');
assert.match(js,/visibilitychange/,'Aufnahme wird beim App-Wechsel nicht beendet');
assert.match(js,/pagehide/,'Aufnahme wird beim Verlassen nicht beendet');
assert.match(js,/insertFromDictation/,'Erkannter Text wird nicht als Diktat an die Suche übergeben');
assert.match(js,/not-allowed/,'Fehlerbehandlung für Mikrofonrechte fehlt');
assert.match(css,/nutritionVoice\.listening/,'Sichtbarer Aufnahmezustand fehlt');
assert.match(css,/prefers-reduced-motion/,'Reduced-Motion-Unterstützung fehlt');
assert.match(version,/const RELEASE='1\.1\.1 Alpha'/,'Sichtbare Version ist nicht 1.1.1 Alpha');
assert.match(version,/nutrition-voice-111\.js\?v=1\.1\.1-alpha/,'Voice-Modul wird nicht geladen');
assert.match(manifest,/version:'1\.1\.1-alpha'/,'Cacheversion ist nicht 1.1.1 Alpha');
assert.match(manifest,/nutrition-voice-111\.css\?v=1\.1\.1-alpha/,'Voice-CSS fehlt im Offline-Cache');
assert.match(manifest,/nutrition-voice-111\.js\?v=1\.1\.1-alpha/,'Voice-JavaScript fehlt im Offline-Cache');
assert.match(sw,/runtime-manifest\.js\?v=1\.1\.1-alpha/,'Service Worker lädt falsches Manifest');
assert.match(update,/sw\.js\?v=1\.1\.1-alpha-force/,'Update-Seite installiert nicht 1.1.1 Alpha');
console.log('CutCoach 1.1.1 Alpha nutrition voice stabilization test: ok');
