'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const project=path.resolve(__dirname,'..');
const js=fs.readFileSync(path.join(project,'nutrition-voice-111.js'),'utf8');
const css=fs.readFileSync(path.join(project,'nutrition-voice-111.css'),'utf8');
const version=fs.readFileSync(path.join(project,'version-v7.js'),'utf8');
const manifest=fs.readFileSync(path.join(project,'runtime-manifest.js'),'utf8');
const sw=fs.readFileSync(path.join(project,'sw.js'),'utf8');
const update=fs.readFileSync(path.join(project,'update.html'),'utf8');
assert.ok(js.includes('SpeechRecognition||window.webkitSpeechRecognition'));
assert.ok(js.includes('stopImmediatePropagation'));
assert.ok(js.includes('aria-pressed'));
assert.ok(js.includes('12000'));
assert.ok(js.includes('visibilitychange'));
assert.ok(js.includes('pagehide'));
assert.ok(js.includes('insertFromDictation'));
assert.ok(js.includes('not-allowed'));
assert.ok(css.includes('nutritionVoice.listening'));
assert.ok(css.includes('prefers-reduced-motion'));
assert.ok(version.includes("const RELEASE='1.2.0 Alpha'"));
assert.ok(version.includes('nutrition-voice-111.js?v=1.1.1-alpha'));
assert.ok(manifest.includes("version:'1.2.0-alpha'"));
assert.ok(manifest.includes('nutrition-voice-111.css?v=1.1.1-alpha'));
assert.ok(manifest.includes('nutrition-voice-111.js?v=1.1.1-alpha'));
assert.ok(sw.includes('runtime-manifest.js?v=1.2.0-alpha'));
assert.ok(update.includes('sw.js?v=1.2.0-alpha-force'));
console.log('CutCoach 1.2.0 Alpha nutrition voice stabilization test: ok');