'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const project=path.resolve(__dirname,'..');
const js=fs.readFileSync(path.join(project,'nutrition-multisearch-120.js'),'utf8');
const css=fs.readFileSync(path.join(project,'nutrition-multisearch-120.css'),'utf8');
const intelligent=fs.readFileSync(path.join(project,'nutrition-multisearch-canonical-128.js'),'utf8');
const version=fs.readFileSync(path.join(project,'version-v7.js'),'utf8');
const manifest=fs.readFileSync(path.join(project,'runtime-manifest.js'),'utf8');
const sw=fs.readFileSync(path.join(project,'sw.js'),'utf8');
const update=fs.readFileSync(path.join(project,'update.html'),'utf8');
assert.match(js,/Mehrfachsuche erkannt/,'Legacy-Mehrfachsuche fehlt');
assert.match(js,/und\|plus\|sowie/,'Konjunktionen werden nicht erkannt');
assert.match(js,/Alle hinzufügen/,'Gemeinsames Hinzufügen fehlt');
assert.match(js,/data-multi-add/,'Einzelnes Hinzufügen fehlt');
assert.match(js,/addCatalogItemToDay/,'Katalogtreffer können nicht hinzugefügt werden');
assert.match(js,/addItemToDay/,'Persönliche Treffer können nicht hinzugefügt werden');
assert.match(js,/numberWords/,'Gesprochene Mengen werden nicht erkannt');
assert.match(js,/DEBOUNCE_MS=220/,'Tippeingaben werden nicht entprellt');
assert.doesNotMatch(js,/observer\.observe\(document\.body/,'Globale DOM-Beobachtung verursacht weiterhin unnötige Renderläufe');
assert.match(intelligent,/Intelligente Suche/,'Neue Funktionsbezeichnung fehlt');
assert.match(intelligent,/parseSequential/,'Mehrfacheingaben ohne Trennwort werden nicht erkannt');
assert.match(intelligent,/quantityOf/,'Mengenparser fehlt');
assert.match(intelligent,/strictCatalogMatch/,'Strikte Einzelauflösung fehlt');
assert.match(intelligent,/buildExactIndex/,'Gecachter Exaktindex fehlt');
assert.match(intelligent,/likelyMulti/,'Schnelle Mehrfacherkennung fehlt');
assert.match(intelligent,/DEBOUNCE_MS=180/,'Optimiertes Debounce fehlt');
assert.match(intelligent,/data-canonical-search/,'Unsichere Begriffe können nicht einzeln weitergesucht werden');
assert.match(intelligent,/node\.dataset\.query/,'Veraltete Mehrfachtreffer werden nicht geprüft');
assert.match(intelligent,/kaesebrot/,'Käsebrot-Standardtreffer fehlt');
assert.match(css,/nutrition-multi-list/,'Mehrfachtreffer sind nicht gestaltet');
assert.match(version,/const RELEASE='1\.2\.1 Alpha'/,'Sichtbare Version ist nicht 1.2.1 Alpha');
assert.match(version,/nutrition-multisearch-canonical-128\.js\?v=1\.2\.10-alpha/,'Intelligente Suchlogik wird nicht geladen');
assert.match(manifest,/version:'1\.2\.6-alpha'/,'Cacheversion ist nicht 1.2.6 Alpha');
assert.match(manifest,/nutrition-multisearch-canonical-128\.js\?v=1\.2\.10-alpha/,'Intelligente Suchlogik fehlt im Cache');
assert.match(sw,/runtime-manifest\.js\?v=1\.2\.6-alpha/,'Service Worker lädt falsches Manifest');
assert.match(update,/sw\.js\?v=1\.2\.6-alpha-force/,'Update-Seite installiert nicht 1.2.6 Alpha');
console.log('CutCoach intelligent multi-search QA with 1.2.6 runtime: ok');