'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const project=path.resolve(__dirname,'..');
const compatibility=fs.readFileSync(path.join(project,'nutrition-multisearch-120.js'),'utf8');
const hardening=fs.readFileSync(path.join(project,'nutrition-search-confidence-hardening-v151.js'),'utf8');
const portionProfiles=fs.readFileSync(path.join(project,'nutrition-portion-profiles-v153.js'),'utf8');
const portionHardening=fs.readFileSync(path.join(project,'nutrition-portion-hardening-v153.js'),'utf8');
const css=fs.readFileSync(path.join(project,'nutrition-multisearch-120.css'),'utf8');
const confidenceCss=fs.readFileSync(path.join(project,'nutrition-search-confidence-v150.css'),'utf8');
const intelligent=fs.readFileSync(path.join(project,'nutrition-multisearch-canonical-128.js'),'utf8');
const version=fs.readFileSync(path.join(project,'version-v7.js'),'utf8');
const manifest=fs.readFileSync(path.join(project,'runtime-manifest.js'),'utf8');
const sw=fs.readFileSync(path.join(project,'sw.js'),'utf8');
const update=fs.readFileSync(path.join(project,'update.html'),'utf8');
assert.match(compatibility,/compatibility-facade/,'Kompatibilitätsfassade fehlt');
assert.match(compatibility,/engine\(\)/,'Fassade delegiert nicht an die zentrale Engine');
assert.match(compatibility,/engine\(\)\?\.parse/,'Alte parse-API wird nicht delegiert');
assert.match(compatibility,/engine\(\)\?\.rowsFor/,'Alte Ergebnis-API wird nicht delegiert');
assert.match(compatibility,/refreshCurrent/,'Alte refresh-API wird nicht delegiert');
assert.match(compatibility,/row\?\.confidence/,'Confidence Score wird nicht durch die Fassade gereicht');
assert.match(compatibility,/nutrition-portion-profiles-v153/,'Portionsprofile werden nicht abgesichert');
assert.match(compatibility,/nutrition-portion-hardening-v153/,'Portions-Hardening wird nicht abgesichert');
assert.match(compatibility,/confidence-hardening-v151/,'Generischer Resolver wird nicht nachgeladen');
assert.doesNotMatch(compatibility,/addEventListener|setTimeout|requestIdleCallback|innerHTML|CutCoachLibrary/,'Kompatibilitätsbrücke enthält eigene Suchlogik');
assert.match(hardening,/ranked-personal/,'Persönliche Trefferpriorisierung fehlt');
assert.match(hardening,/collectGeneric/,'Generischer Vollkatalog-Resolver fehlt');
assert.match(hardening,/tokenMatches/,'Tokenbasierte Katalogauflösung fehlt');
assert.match(hardening,/data-confidence-choice/,'Mehrdeutige Treffer sind nicht auswählbar');
assert.match(hardening,/loadedBeforeEngine/,'Upgradepfad für bereits geladene Engine fehlt');
assert.match(portionProfiles,/profile\('toast'/,'Toast-Portionsprofil fehlt');
assert.match(portionProfiles,/conservativeFallback/,'Konservativer Portionsfallback fehlt');
assert.match(portionHardening,/portionNeedsReview/,'Unsichere Haushaltsmengen werden nicht geschützt');
assert.match(portionHardening,/food-specific-portions/,'Portionsbuild fehlt');
assert.match(intelligent,/Intelligente Suche/,'Zentrale Suchbezeichnung fehlt');
assert.match(intelligent,/parseSequential/,'Mehrfacheingaben ohne Trennwort werden nicht erkannt');
assert.match(intelligent,/expandWith/,'Mehrfacheingaben mit Verknüpfungen werden nicht erkannt');
assert.match(intelligent,/parseCompound/,'Zusammengesetzte Lebensmittelbegriffe werden nicht erkannt');
assert.match(intelligent,/CONNECTOR_RE/,'Natürliche Verknüpfungen fehlen');
assert.match(intelligent,/quantityOf/,'Mengenparser fehlt');
assert.match(intelligent,/strictCatalogMatchInfo/,'Strikte Einzelauflösung fehlt');
assert.match(intelligent,/buildExactIndex/,'Gecachter Exaktindex fehlt');
assert.match(intelligent,/likelyMulti/,'Schnelle Mehrfacherkennung fehlt');
assert.match(intelligent,/SAFE_CONFIDENCE=90/,'Sichere Confidence-Schwelle fehlt');
assert.match(intelligent,/REVIEW_CONFIDENCE=72/,'Prüfschwelle fehlt');
assert.match(css,/nutrition-multi-list/,'Mehrfachtreffer sind nicht gestaltet');
assert.match(confidenceCss,/nutrition-confidence/,'Confidence-Anzeige ist nicht gestaltet');
assert.match(confidenceCss,/confidence-choice-list/,'Mehrdeutigkeitsauswahl ist nicht gestaltet');
assert.match(version,/nutrition-portion-profiles-v153\.js\?v=1\.5\.3-alpha/,'Portionsprofile werden nicht zuerst geladen');
assert.match(version,/nutrition-portion-hardening-v153\.js\?v=1\.5\.3-alpha/,'Portions-Hardening wird nicht geladen');
assert.match(version,/nutrition-search-confidence-hardening-v151\.js\?v=1\.5\.2-alpha/,'Vollkatalog-Resolver wird nicht geladen');
assert.match(version,/nutrition-multisearch-canonical-128\.js\?v=1\.5\.0-alpha/,'Zentrale Suchlogik wird nicht geladen');
assert.match(version,/nutrition-multisearch-120\.js\?v=1\.5\.3-compat/,'Produktiver Loaderpfad der Fassade fehlt');
assert.match(manifest,/nutrition-portion-profiles-v153\.js\?v=1\.5\.3-alpha/,'Portionsprofile fehlen im Cache');
assert.match(manifest,/nutrition-portion-hardening-v153\.js\?v=1\.5\.3-alpha/,'Portions-Hardening fehlt im Cache');
assert.match(manifest,/nutrition-search-confidence-hardening-v151\.js\?v=1\.5\.2-alpha/,'Generischer Resolver fehlt im Cache');
assert.match(manifest,/nutrition-multisearch-canonical-128\.js\?v=1\.5\.0-alpha/,'Zentrale Suchlogik fehlt im Cache');
assert.match(manifest,/nutrition-multisearch-120\.js\?v=1\.5\.3-compat/,'Produktive Kompatibilitäts-URL fehlt im Cache');
assert.match(sw,/search153-portions/,'Portions-Cachegeneration fehlt');
assert.match(update,/sw\.js\?v=1\.2\.6-alpha-force/,'Update-Seite installiert nicht 1.2.6 Alpha');
console.log('CutCoach lebensmittelbezogene Portionsumrechnung 1.5.3 QA: ok');