'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const project=path.resolve(__dirname,'..');
const engine=fs.readFileSync(path.join(project,'nutrition-multisearch-canonical-128.js'),'utf8');
const compatibility=fs.readFileSync(path.join(project,'nutrition-multisearch-120.js'),'utf8');
assert.match(engine,/strictCatalogMatchInfo/,'Strikte Exaktauflösung fehlt');
assert.match(engine,/exactMatchInfo/,'Alias- und Exakttreffer fehlen');
assert.match(engine,/safeFuzzyMatchInfo/,'Sichere Tippfehlerauflösung fehlt');
assert.match(engine,/distanceWithin/,'Begrenzte Distanzprüfung fehlt');
assert.match(engine,/matchType/,'Trefferart wird nicht dokumentiert');
assert.match(engine,/corrected/,'Korrigierte Treffer werden nicht ausgewiesen');
assert.match(engine,/incompatible/,'Unpassende Einheiten werden nicht erkannt');
assert.match(engine,/SAFE_CONFIDENCE=90/,'Sichere Confidence-Schwelle fehlt');
assert.match(engine,/REVIEW_CONFIDENCE=72/,'Prüfschwelle fehlt');
assert.match(engine,/rankExactCandidates/,'Trefferrangfolge fehlt');
assert.match(engine,/Kein sicherer Treffer/,'Unsichere Treffer werden nicht abgefangen');
assert.match(compatibility,/confidence:Number\(row\?\.confidence\)\|\|0/,'Alte resolve-API erhält keinen delegierten Confidence Score');
assert.match(compatibility,/alternatives:Object\.freeze\(\[\.\.\.\(row\?\.alternatives\|\|\[\]\)\]\)/,'Kompatibilitätsantwort reicht Alternativen nicht durch');
assert.doesNotMatch(compatibility,/candidateType|canonicalScore|genericScore/,'Trefferbewertung ist weiterhin doppelt implementiert');
console.log('CutCoach central Confidence Score and passive compatibility: ok');