'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const project=path.resolve(__dirname,'..');
const engine=fs.readFileSync(path.join(project,'nutrition-multisearch-canonical-128.js'),'utf8');
const compatibility=fs.readFileSync(path.join(project,'nutrition-multisearch-120.js'),'utf8');
assert.match(engine,/strictCatalogMatch/,'Strikte Exaktauflösung fehlt');
assert.match(engine,/exactMatch/,'Alias- und Exakttreffer fehlen');
assert.match(engine,/safeFuzzyMatch/,'Sichere Tippfehlerauflösung fehlt');
assert.match(engine,/distanceWithin/,'Begrenzte Distanzprüfung fehlt');
assert.match(engine,/matchType/,'Trefferart wird nicht dokumentiert');
assert.match(engine,/corrected/,'Korrigierte Treffer werden nicht ausgewiesen');
assert.match(engine,/incompatible/,'Unpassende Einheiten werden nicht erkannt');
assert.match(engine,/spezi/,'Spezi-Standardtreffer fehlt');
assert.match(engine,/Kein sicherer Treffer/,'Unsichere Treffer werden nicht abgefangen');
assert.match(compatibility,/confidence:row\?\.item/,'Alte resolve-API erhält keinen delegierten Vertrauenswert');
assert.match(compatibility,/alternatives:Object\.freeze\(\[\]\)/,'Kompatibilitätsantwort bleibt strukturell stabil');
assert.doesNotMatch(compatibility,/candidateType|canonicalScore|genericScore/,'Trefferbewertung ist weiterhin doppelt implementiert');
console.log('CutCoach central search accuracy and passive compatibility: ok');