'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const project=path.resolve(__dirname,'..');
const engine=fs.readFileSync(path.join(project,'nutrition-multisearch-canonical-128.js'),'utf8');
const compatibility=fs.readFileSync(path.join(project,'nutrition-multisearch-120.js'),'utf8');
assert.match(engine,/strictCatalogMatch/,'Exakte Katalogauflösung fehlt');
assert.match(engine,/exactMatch/,'Exakte Aliasauflösung fehlt');
assert.match(engine,/part\.directItem/,'Bereits exakt erkannte Begriffe werden nicht priorisiert');
assert.match(engine,/if\(wholeRow\.item/,'Vollständige Gerichtenamen werden nicht vor Zerlegung geschützt');
assert.match(engine,/Cola ohne Zucker|cola ohne zucker/,'Eindeutige Getränkebezeichnung fehlt');
assert.match(engine,/COMPOUNDS/,'Bewusste Kompositauflösung fehlt');
assert.doesNotMatch(compatibility,/wholeWordMatch|COMPOUND_BLOCKLIST|genericDrinkPriority|exactIntent/,'Exakte Suchabsicht ist weiterhin doppelt implementiert');
console.log('CutCoach exact intent is owned by the central search engine: ok');