'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const project=path.resolve(__dirname,'..');
const js=fs.readFileSync(path.join(project,'nutrition-multisearch-120.js'),'utf8');
const canonical=fs.readFileSync(path.join(project,'nutrition-multisearch-canonical-126.js'),'utf8');
const version=fs.readFileSync(path.join(project,'version-v7.js'),'utf8');
const manifest=fs.readFileSync(path.join(project,'runtime-manifest.js'),'utf8');
const sw=fs.readFileSync(path.join(project,'sw.js'),'utf8');
const update=fs.readFileSync(path.join(project,'update.html'),'utf8');
assert.match(js,/const DEBOUNCE_MS=220/,'Debounce fehlt');
assert.match(js,/const CACHE_MS=30000/,'Katalogcache fehlt');
assert.match(js,/requestIdleCallback/,'Leerlauf-Rendering fehlt');
assert.doesNotMatch(js,/MutationObserver/,'Globale DOM-Beobachtung ist noch aktiv');
assert.match(js,/spezi:\{type:'drink'/,'Spezi-Profil fehlt');
assert.match(js,/cola:\{type:'drink'/,'Cola-Profil fehlt');
assert.match(js,/blocked:\['bier'/,'Getränke-Blockliste fehlt');
assert.match(js,/lahmacun/,'Gerichte werden für Getränkesuchen nicht blockiert');
assert.match(canonical,/CATALOG_IDS/,'Deterministische Alltagsgerichte fehlen');
assert.match(canonical,/recognizedRows/,'Vollständige Satzzerlegung fehlt');
assert.match(version,/const RELEASE='1\.2\.1 Alpha'/);
assert.match(version,/nutrition-multisearch-canonical-126\.js\?v=1\.2\.6-alpha/);
assert.match(manifest,/version:'1\.2\.2-alpha'/);
assert.match(manifest,/nutrition-multisearch-canonical-126\.js\?v=1\.2\.6-alpha/);
assert.match(sw,/runtime-manifest\.js\?v=1\.2\.2-alpha/);
assert.match(update,/sw\.js\?v=1\.2\.2-alpha-force/);
console.log('CutCoach 1.2.1 Alpha multisearch with 1.2.2 runtime: ok');