'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const project=path.resolve(__dirname,'..');
const compatibility=fs.readFileSync(path.join(project,'nutrition-multisearch-120.js'),'utf8');
const learning=fs.readFileSync(path.join(project,'nutrition-search-learning-v161.js'),'utf8');
const exactWhole=fs.readFileSync(path.join(project,'nutrition-search-exact-whole-v170.js'),'utf8');
const hardening=fs.readFileSync(path.join(project,'nutrition-search-confidence-hardening-v151.js'),'utf8');
const portionProfiles=fs.readFileSync(path.join(project,'nutrition-portion-profiles-v153.js'),'utf8');
const portionHardening=fs.readFileSync(path.join(project,'nutrition-portion-hardening-v153.js'),'utf8');
const intelligent=fs.readFileSync(path.join(project,'nutrition-multisearch-canonical-128.js'),'utf8');
const voice=fs.readFileSync(path.join(project,'nutrition-voice-111.js'),'utf8');
const performance=fs.readFileSync(path.join(project,'nutrition-v110.js'),'utf8');
const enhanced=fs.readFileSync(path.join(project,'nutrition-v73.js'),'utf8');
const version=fs.readFileSync(path.join(project,'version-v7.js'),'utf8');
const manifest=fs.readFileSync(path.join(project,'runtime-manifest.js'),'utf8');
const sw=fs.readFileSync(path.join(project,'sw.js'),'utf8');
const update=fs.readFileSync(path.join(project,'update.html'),'utf8');
assert.match(compatibility,/const VERSION='1\.9\.6-compat'/,'Kompatibilitätsversion fehlt');
assert.match(compatibility,/mode:'compatibility-facade'/,'Fassade ist nicht gekennzeichnet');
assert.match(compatibility,/CutCoachIntelligentSearch128/,'Fassade delegiert nicht an die zentrale Engine');
assert.match(compatibility,/attachLayers/,'Suchschichten werden nicht zentral angehängt');
assert.match(compatibility,/status:'multiple'/,'Mehrfachergebnisse werden nicht eindeutig gekennzeichnet');
assert.match(compatibility,/nutrition-portion-profiles-v153/,'Portionsprofile werden nicht abgesichert');
assert.match(compatibility,/nutrition-portion-hardening-v153/,'Portions-Hardening wird nicht abgesichert');
assert.match(compatibility,/nutrition-search-learning-v161/,'Gehärtete Lernschicht wird nicht abgesichert');
assert.match(compatibility,/nutrition-search-exact-whole-v170/,'Vollnamenschutz wird nicht abgesichert');
assert.match(compatibility,/nutrition-search-exact-whole-v170\.js\?v=1\.9\.6-alpha/,'Fassade lädt nicht den aktuellen Artikel-/Sequenzschutz');
assert.doesNotMatch(compatibility,/addEventListener|setTimeout|requestIdleCallback|innerHTML|CutCoachLibrary/,'Kompatibilitätsbrücke enthält eine zweite Suchlogik');
assert.match(learning,/stage4-hardening/,'Stufe-4-Hardening fehlt');
assert.match(learning,/revertToken/,'Undo des Lernsignals fehlt');
assert.match(learning,/handleStorage/,'Tab-Synchronisierung fehlt');
assert.match(exactWhole,/1\.9\.6-article-sequence/,'Artikel- und Sequenzintegrität fehlt');
assert.match(exactWhole,/recognizedBaseRows/,'Interne Standardtreffer werden nicht in Sequenzen übernommen');
assert.match(exactWhole,/protectedRows/,'Vollständige Katalognamen werden nicht geschützt');
assert.match(exactWhole,/protectedSequenceRows/,'Vollständige Katalognamen werden innerhalb von Kombinationen nicht geschützt');
assert.match(exactWhole,/ambiguous-exact-whole/,'Namenskollisionen werden nicht bewusst mehrdeutig gehalten');
assert.match(exactWhole,/cleanNatural/,'Natürliche Sprache wird nicht vor dem Vollnamensabgleich bereinigt');
assert.match(exactWhole,/invalidQuantity/,'Ungültige Mengen werden nicht sicher abgefangen');
assert.match(hardening,/search-integrity/,'A–Z-Ranking-Integrität fehlt');
assert.match(hardening,/loadedBeforeEngine/,'Bereits geladene Engine wird nicht gehärtet');
assert.match(hardening,/installFallbackObserver/,'Begrenzter Upgrade-Beobachter fehlt');
assert.match(hardening,/ranked-personal/,'Persönliche Treffer werden nicht priorisiert');
assert.match(hardening,/collectGeneric/,'Generische Katalogauflösung fehlt');
assert.match(hardening,/tokenMatches/,'Tokenbasierte Lebensmittelauflösung fehlt');
assert.match(hardening,/data-confidence-choice/,'Mehrdeutigkeitsauswahl fehlt');
assert.match(portionProfiles,/directMeasures/,'Lebensmitteleigene Portionsangaben werden nicht gelesen');
assert.match(portionProfiles,/conservativeFallback/,'Unsichere Haushaltsmaße werden nicht konservativ behandelt');
assert.match(portionHardening,/portionNeedsReview/,'Unsichere Portionen werden nicht markiert');
assert.match(portionHardening,/hasHouseholdInput/,'Haushaltsmengen werden nicht gezielt übernommen');
assert.match(portionHardening,/kind:'choice'/,'Haushaltsauswahl wird nicht gelernt');
assert.match(intelligent,/parseSequential/,'Folgen ohne Trennwort werden nicht zerlegt');
assert.match(intelligent,/expandWith/,'Natürliche Kombinationen werden nicht zerlegt');
assert.match(intelligent,/parseCompound/,'Zusammengesetzte Begriffe fehlen');
assert.match(intelligent,/buildExactIndex/,'Exaktindex fehlt');
assert.match(intelligent,/SAFE_CONFIDENCE=90/,'Confidence-Sicherheitsgrenze fehlt');
assert.match(intelligent,/REVIEW_CONFIDENCE=72/,'Confidence-Prüfgrenze fehlt');
assert.match(voice,/updatePreview/,'Mikrofonvorschau fehlt');
assert.match(voice,/dispatchSearch\(result\)/,'Sprachsuche wird nicht final übergeben');
assert.match(voice,/sessionActive/,'Symmetrischer Sprachlebenszyklus fehlt');
assert.doesNotMatch(voice,/dispatchSearch\(preview\)/,'Interim-Sprache löst weiterhin vollständige Suchen aus');
assert.doesNotMatch(performance,/characterData:true/,'Nutrition-Observer beobachtet weiterhin unnötige Textänderungen');
assert.doesNotMatch(performance,/version\.textContent/,'Nutrition-Modul überschreibt weiterhin die App-Version');
assert.doesNotMatch(enhanced,/observe\(document\.documentElement/,'Alltags-Enhancer beobachtet weiterhin die gesamte App');
assert.match(enhanced,/clearInjected/,'Alte Alltags-Treffer werden bei Query-Wechsel nicht entfernt');
assert.match(version,/nutrition-portion-profiles-v153\.js\?v=1\.5\.3-alpha/);
assert.match(version,/nutrition-portion-hardening-v153\.js\?v=1\.9\.0-alpha/);
assert.match(version,/nutrition-search-learning-v161\.js\?v=1\.6\.1-alpha/);
assert.match(version,/nutrition-search-exact-whole-v170\.js\?v=1\.9\.6-alpha/);
assert.match(version,/nutrition-search-confidence-hardening-v151\.js\?v=1\.9\.0-alpha/);
assert.match(version,/nutrition-multisearch-canonical-128\.js\?v=1\.5\.0-alpha/);
assert.match(version,/nutrition-multisearch-120\.js\?v=1\.9\.6-compat/);
assert.match(version,/nutrition-search-confidence-v150\.css\?v=1\.7\.1-alpha/);
assert.match(manifest,/nutrition-portion-profiles-v153\.js\?v=1\.5\.3-alpha/);
assert.match(manifest,/nutrition-portion-hardening-v153\.js\?v=1\.9\.0-alpha/);
assert.match(manifest,/nutrition-search-learning-v161\.js\?v=1\.6\.1-alpha/);
assert.match(manifest,/nutrition-search-exact-whole-v170\.js\?v=1\.9\.6-alpha/);
assert.match(manifest,/nutrition-search-confidence-hardening-v151\.js\?v=1\.9\.0-alpha/);
assert.match(manifest,/nutrition-multisearch-120\.js\?v=1\.9\.6-compat/);
assert.match(manifest,/nutrition-search-confidence-v150\.css\?v=1\.7\.1-alpha/);
assert.match(sw,/runtime-manifest\.js\?v=1\.2\.7-alpha/);
assert.match(sw,/search153-portions/);
assert.match(sw,/search161-hardening/);
assert.match(sw,/search170-exact-whole/);
assert.match(sw,/search171-edge-hardening/);
assert.match(sw,/stage6-production180/);
assert.match(sw,/search190-integrity/);
assert.match(sw,/search196-article-sequence/);
assert.match(update,/sw\.js\?v=1\.2\.7-alpha-force-search196/);
console.log('CutCoach nutrition stability with article and sequence search integrity 1.9.6: ok');