'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const project=path.resolve(__dirname,'..');
const js=fs.readFileSync(path.join(project,'nutrition-multisearch-120.js'),'utf8');
const intelligent=fs.readFileSync(path.join(project,'nutrition-multisearch-canonical-128.js'),'utf8');
const version=fs.readFileSync(path.join(project,'version-v7.js'),'utf8');
const manifest=fs.readFileSync(path.join(project,'runtime-manifest.js'),'utf8');
const sw=fs.readFileSync(path.join(project,'sw.js'),'utf8');
const update=fs.readFileSync(path.join(project,'update.html'),'utf8');
assert.match(js,/const DEBOUNCE_MS=220/,'Debounce fehlt');
assert.match(js,/const CACHE_MS=30000/,'Katalogcache fehlt');
assert.match(js,/requestIdleCallback/,'Leerlauf-Rendering fehlt');
assert.doesNotMatch(js,/MutationObserver/,'Globale DOM-Beobachtung ist noch aktiv');
assert.match(js,/spezi:\{type:'drink'/,'Spezi-Profil fehlt');
assert.match(js,/cola:\{type:'drink'/,'Cola-Profil fehlt');
assert.match(js,/blocked:\['bier'/,'Getränke-Blockliste fehlt');
assert.match(js,/lahmacun/,'Gerichte werden für Getränkesuchen nicht blockiert');
assert.match(intelligent,/parseSequential/,'Folgen ohne Trennwort werden nicht zerlegt');
assert.match(intelligent,/quantityTokens/,'Mengenwörter fehlen');
assert.match(intelligent,/rowsFor/,'Vollständige Satzzerlegung fehlt');
assert.match(intelligent,/strictCatalogMatch/,'Strikte Katalogauflösung fehlt');
assert.match(intelligent,/Kein sicherer Treffer/,'Unsichere Treffer werden nicht abgefangen');
assert.match(intelligent,/Intelligente Suche/,'Funktionsname ist nicht sichtbar');
assert.match(version,/const RELEASE='1\.2\.1 Alpha'/);
assert.match(version,/nutrition-multisearch-canonical-128\.js\?v=1\.2\.8-alpha/);
assert.match(manifest,/version:'1\.2\.4-alpha'/);
assert.match(manifest,/nutrition-multisearch-canonical-128\.js\?v=1\.2\.8-alpha/);
assert.match(sw,/runtime-manifest\.js\?v=1\.2\.4-alpha/);
assert.match(update,/sw\.js\?v=1\.2\.4-alpha-force/);
console.log('CutCoach intelligent search stability with 1.2.4 runtime: ok');