'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {JSDOM}=require('jsdom');
const root=path.resolve(__dirname,'..');
const profiles=fs.readFileSync(path.join(root,'nutrition-portion-profiles-v153.js'),'utf8');
const portions=fs.readFileSync(path.join(root,'nutrition-portion-hardening-v153.js'),'utf8');
const learning=fs.readFileSync(path.join(root,'nutrition-search-learning-v161.js'),'utf8');
const exactWhole=fs.readFileSync(path.join(root,'nutrition-search-exact-whole-v170.js'),'utf8');
const hardening=fs.readFileSync(path.join(root,'nutrition-search-confidence-hardening-v151.js'),'utf8');
const canonical=fs.readFileSync(path.join(root,'nutrition-multisearch-canonical-128.js'),'utf8');
const compatibility=fs.readFileSync(path.join(root,'nutrition-multisearch-120.js'),'utf8');
const loader=fs.readFileSync(path.join(root,'version-v7.js'),'utf8');
const manifest=fs.readFileSync(path.join(root,'runtime-manifest.js'),'utf8');
const sw=fs.readFileSync(path.join(root,'sw.js'),'utf8');
assert.match(compatibility,/mode:'compatibility-facade'/);
assert.match(compatibility,/const VERSION='1\.7\.0-compat'/);
assert.match(compatibility,/attachLayers/);
assert.match(compatibility,/nutrition-portion-profiles-v153/);
assert.match(compatibility,/nutrition-portion-hardening-v153/);
assert.match(compatibility,/nutrition-search-learning-v161/);
assert.match(compatibility,/nutrition-search-exact-whole-v170/);
assert.doesNotMatch(compatibility,/addEventListener\s*\(|setTimeout|setInterval|requestAnimationFrame|requestIdleCallback|innerHTML|CutCoachLibrary/);
assert.match(portions,/const VERSION='1\.5\.3-alpha'/);
assert.match(portions,/food-specific-portions/);
assert.match(portions,/portionVersion/);
assert.match(learning,/const VERSION='1\.6\.1-alpha'/);
assert.match(learning,/stage4-hardening/);
assert.match(learning,/MAX_AGE_MS=180/);
assert.match(learning,/revertToken/);
assert.match(learning,/handleStorage/);
assert.match(exactWhole,/const VERSION='1\.7\.0-alpha'/);
assert.match(exactWhole,/exact-whole-protection/);
assert.match(exactWhole,/protectedRows/);
assert.match(hardening,/const VERSION='1\.6\.1-alpha'/);
assert.match(hardening,/baseVersion/);
assert.match(hardening,/ranked-personal/);
assert.match(hardening,/ranked-local-learning/);
assert.match(hardening,/collectGeneric/);
assert.match(hardening,/data-confidence-choice/);
const dom=new JSDOM('<!doctype html><body data-nutrition-meal-type="Snack"><section data-screen="food" class="active"><div class="nutrition-search-card"><input id="nutritionSearch"></div><div class="nutrition-results"></div></section></body>',{url:'https://example.test/cutcoach/',runScripts:'dangerously',pretendToBeVisual:true});
const {window}=dom;
window.CutCoachFoodCatalog={items:()=>[],get:()=>null};window.CutCoachLibrary={exportData:()=>({items:[]}),addItemToDay:()=>true,addCatalogItemToDay:()=>true,undoDayAdd:()=>true};window.CutCoachEverydayCatalog={items:()=>[],get:()=>null};window.render=()=>{};window.toast=()=>{};
let listenerCount=0;const nativeAdd=window.document.addEventListener.bind(window.document);window.document.addEventListener=(...args)=>{listenerCount++;return nativeAdd(...args)};
for(const source of [profiles,portions,learning,exactWhole,hardening,canonical]){const script=window.document.createElement('script');script.textContent=source;window.document.head.append(script)}
let engine=window.CutCoachIntelligentSearch128;engine=window.CutCoachSearchExactWhole170.attach(engine);engine=window.CutCoachSearchConfidenceHardening151.attach(engine);engine=window.CutCoachPortionHardening153.attach(engine);const activeEngineListeners=listenerCount;assert.ok(activeEngineListeners>0);
const facadeScript=window.document.createElement('script');facadeScript.textContent=compatibility;window.document.head.append(facadeScript);assert.equal(listenerCount,activeEngineListeners,'Passive Kompatibilitätsbrücke registriert zusätzliche Dokument-Listener.');
const facade=window.CutCoachNutritionMultiSearch120;engine=window.CutCoachIntelligentSearch128;assert.ok(engine);assert.ok(facade);assert.equal(engine.version,'1.5.3-alpha');assert.equal(engine.build,'1.5.3-food-specific-portions');assert.equal(engine.learningVersion,'1.6.1-alpha');assert.equal(engine.exactWholeVersion,'1.7.0-alpha');assert.equal(facade.mode,'compatibility-facade');assert.equal(facade.engineVersion(),engine.version);
const direct=engine.rowsFor('Sucuk mit Toast'),delegated=facade.rowsFor('Sucuk mit Toast');assert.deepEqual(Array.from(delegated,row=>row.item?.name),Array.from(direct,row=>row.item?.name));
const resolved=facade.resolve('Sucuk');assert.equal(resolved.match?.name,'Sucuk');assert.equal(resolved.confidence,100);assert.equal(resolved.status,'matched');assert.equal(resolved.personalReason,'');
const portion=facade.resolve('1 EL Butter');assert.match(portion.amountLabel,/15 g/);assert.match(String(portion.portionSource),/profile:butter/);
assert.match(loader,/const loadCanonical=\(\)=>ensure\('nutrition-intelligent-search-128','\.\/nutrition-multisearch-canonical-128\.js\?v=1\.5\.0-alpha'/);
assert.match(loader,/const loadConfidence=\(\)=>ensure\('nutrition-search-confidence-hardening-v151','\.\/nutrition-search-confidence-hardening-v151\.js\?v=1\.6\.1-alpha'/);
assert.match(loader,/const loadExactWhole=\(\)=>ensure\('nutrition-search-exact-whole-v170','\.\/nutrition-search-exact-whole-v170\.js\?v=1\.7\.0-alpha'/);
assert.match(loader,/const loadLearning=\(\)=>ensure\('nutrition-search-learning-v161','\.\/nutrition-search-learning-v161\.js\?v=1\.6\.1-alpha'/);
assert.match(loader,/const loadPortionHardening=\(\)=>ensure\('nutrition-portion-hardening-v153','\.\/nutrition-portion-hardening-v153\.js\?v=1\.5\.3-alpha'/);
assert.match(loader,/nutrition-multisearch-120\.js\?v=1\.7\.0-compat/);assert.doesNotMatch(loader,/loadLegacy/);
assert.match(manifest,/nutrition-portion-profiles-v153\.js\?v=1\.5\.3-alpha/);assert.match(manifest,/nutrition-portion-hardening-v153\.js\?v=1\.5\.3-alpha/);assert.match(manifest,/nutrition-search-learning-v161\.js\?v=1\.6\.1-alpha/);assert.match(manifest,/nutrition-search-exact-whole-v170\.js\?v=1\.7\.0-alpha/);assert.match(manifest,/nutrition-search-confidence-hardening-v151\.js\?v=1\.6\.1-alpha/);assert.match(manifest,/nutrition-multisearch-120\.js\?v=1\.7\.0-compat/);assert.match(sw,/search153-portions/);assert.match(sw,/search160-learning/);assert.match(sw,/search161-hardening/);assert.match(sw,/search170-exact-whole/);
dom.window.close();console.log('Eine zentrale Such-Engine mit Vollkatalog-, Vollnamen-, Portions- und gehärteter Lernschicht: ok');
