'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{JSDOM}=require('jsdom'),root=path.resolve(__dirname,'..');
const source=fs.readFileSync(path.join(root,'nutrition-multisearch-canonical-128.js'),'utf8'),loader=fs.readFileSync(path.join(root,'version-v7.js'),'utf8'),manifest=fs.readFileSync(path.join(root,'runtime-manifest.js'),'utf8'),sw=fs.readFileSync(path.join(root,'sw.js'),'utf8');
const alpha={id:'catalog-alpha',name:'Alpha',aliases:[],amount:100,unit:'g',calories:100,protein:1,carbs:1,fat:1,source:'cutcoach',catalog:true},beta={id:'catalog-beta',name:'Beta',aliases:[],amount:100,unit:'g',calories:100,protein:1,carbs:1,fat:1,source:'cutcoach',catalog:true},gamma={id:'library-gamma',name:'Gamma',aliases:[],amount:100,unit:'g',calories:100,protein:1,carbs:1,fat:1,source:'user',kind:'food'},delta={id:'library-delta',name:'Delta',aliases:[],amount:100,unit:'g',calories:100,protein:1,carbs:1,fat:1,source:'user',kind:'food'};
const dom=new JSDOM('<body data-nutrition-meal-type="Snack"><div class="nutrition-search-card"><input id="nutritionSearch"></div><section class="nutrition-results" id="visibleResults"></section><section class="nutrition-empty-state" id="hiddenEmpty" hidden></section></body>',{url:'https://example.test/',runScripts:'dangerously',pretendToBeVisual:true}),w=dom.window;let libraryMode='throw',addResult=null;
w.CutCoachLibrary={exportData:()=>{if(libraryMode==='throw')throw Error('unavailable');return{items:libraryMode==='items'?[gamma,delta]:[]}},addCatalogItemToDay:()=>addResult};w.CutCoachFoodCatalog={items:()=>[alpha,beta],get:()=>null};w.CutCoachEverydayCatalog={items:()=>[],get:()=>null};w.render=()=>{};w.toast=()=>{};
let listenerCount=0,nativeAdd=w.document.addEventListener.bind(w.document);w.document.addEventListener=(...args)=>{listenerCount++;return nativeAdd(...args)};let script=w.document.createElement('script');script.textContent=source;w.document.head.append(script);const first=listenerCount;script=w.document.createElement('script');script.textContent=source;w.document.head.append(script);assert.equal(listenerCount,first);
const api=w.CutCoachIntelligentSearch128;assert.equal(api.version,'1.5.0-alpha');assert.deepEqual(Array.from(api.rowsFor('Alpha und Beta'),row=>row.item?.name),['Alpha','Beta']);const input=w.document.querySelector('#nutritionSearch'),visible=w.document.querySelector('#visibleResults'),hidden=w.document.querySelector('#hiddenEmpty');input.value='Sucuk mit Toast';assert.equal(api.render(input),true);assert.equal(visible.hidden,true);assert.equal(hidden.hidden,true);input.value='Sucuk';input.dispatchEvent(new w.Event('input',{bubbles:true}));assert.equal(visible.hidden,false);input.value='Sucuk mit Toast';api.render(input);input.dispatchEvent(new w.Event('compositionstart',{bubbles:true}));input.value='Sucuk';input.dispatchEvent(new w.Event('compositionend',{bubbles:true}));assert.equal(w.document.querySelector('#nutritionMultiSearch').hidden,true);libraryMode='items';input.value='Gamma und Delta';assert.ok(api.rowsFor(input.value).every(row=>!row.item));w.dispatchEvent(new w.CustomEvent('cutcoach:librarychange'));assert.match(w.document.querySelector('#nutritionMultiSearch').textContent,/Gamma/);addResult=null;input.value='Sucuk mit Toast';api.render(input);const addAll=w.document.querySelector('[data-canonical-all]');addAll.dispatchEvent(new w.MouseEvent('click',{bubbles:true}));assert.match(addAll.textContent,/Erneut versuchen/);
assert.match(loader,/nutrition-search-learning-v161\.js\?v=1\.6\.1-alpha/);assert.match(loader,/nutrition-portion-hardening-v153\.js\?v=1\.9\.0-alpha/);assert.match(manifest,/nutrition-search-learning-v161\.js\?v=1\.6\.1-alpha/);assert.match(manifest,/nutrition-portion-hardening-v153\.js\?v=1\.9\.0-alpha/);assert.match(manifest,/nutrition-multisearch-canonical-128\.js\?v=1\.5\.0-alpha/);assert.match(sw,/search153-portions/);assert.match(sw,/search160-learning/);assert.match(sw,/search161-hardening/);assert.match(sw,/search190-integrity/);dom.window.close();console.log('Such-Engine bleibt unter Portions-, Lern- und A–Z-Integrität stabil.');
