'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {JSDOM}=require('jsdom');
const root=path.resolve(__dirname,'..');
const source=fs.readFileSync(path.join(root,'nutrition-multisearch-canonical-128.js'),'utf8');
const compatibility=fs.readFileSync(path.join(root,'nutrition-multisearch-120.js'),'utf8');
const css=fs.readFileSync(path.join(root,'nutrition-search-confidence-v150.css'),'utf8');
const dom=new JSDOM('<body data-nutrition-meal-type="Frühstück"><div class="nutrition-search-card"><input id="nutritionSearch"></div><div class="nutrition-results"></div></body>',{url:'https://example.test/',runScripts:'dangerously'});
const {window}=dom;
const menemen={id:'menemen',name:'Menemen',amount:350,unit:'g',calories:430,protein:23,carbs:20,fat:28,source:'cutcoach'};
window.CutCoachLibrary={exportData:()=>({items:[]}),addCatalogItemToDay:()=>true};
window.CutCoachFoodCatalog={items:()=>[menemen],get:()=>null};
window.CutCoachEverydayCatalog={items:()=>[],get:()=>null};
window.render=()=>{};window.toast=()=>{};
let script=window.document.createElement('script');script.textContent=source;window.document.head.append(script);
script=window.document.createElement('script');script.textContent=compatibility;window.document.head.append(script);
const api=window.CutCoachIntelligentSearch128;
assert.equal(api.version,'1.5.0-alpha');
assert.deepEqual({...api.thresholds},{safe:90,review:72});
const exact=api.rowsFor('1 Sucuk')[0];assert.equal(exact.status,'matched');assert.equal(exact.confidence,100);
const typo=api.rowsFor('Menemem')[0];assert.equal(typo.status,'matched');assert.ok(typo.confidence>=90);
const review=api.rowsFor('Haferflaken')[0];assert.equal(review.status,'review');assert.ok(review.confidence<90);
const input=window.document.querySelector('#nutritionSearch');input.value='Haferflaken mit Toast';assert.equal(api.render(input),true);
const host=window.document.querySelector('#nutritionMultiSearch');assert.ok(host.querySelector('article.review'));assert.equal(host.querySelector('[data-canonical-all]').disabled,true);assert.equal(host.querySelectorAll('[data-canonical-add]').length,1);
const resolved=window.CutCoachNutritionMultiSearch120.resolve('Haferflaken');assert.equal(resolved.confidence,review.confidence);assert.equal(resolved.status,'review');
assert.match(css,/nutrition-confidence/);assert.match(css,/article\.review/);
dom.window.close();
console.log('Confidence Score 1.5.0 geprüft.');