'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {JSDOM}=require('jsdom');
const root=path.resolve(__dirname,'..');
const canonical=fs.readFileSync(path.join(root,'nutrition-multisearch-canonical-128.js'),'utf8');
const hardening=fs.readFileSync(path.join(root,'nutrition-search-confidence-hardening-v151.js'),'utf8');
const compatibility=fs.readFileSync(path.join(root,'nutrition-multisearch-120.js'),'utf8');
const manifest=fs.readFileSync(path.join(root,'runtime-manifest.js'),'utf8');
const personalSkyr={id:'personal-skyr',name:'Skyr',kind:'food',amount:500,unit:'g',calories:315,protein:55,carbs:20,fat:1,source:'user',favorite:true,uses:12};
const personalCola={id:'personal-cola',name:'Cola',kind:'food',amount:500,unit:'ml',calories:210,protein:0,carbs:52,fat:0,source:'off',favorite:true,uses:8};
const a={id:'pudding-a',name:'Protein Pudding',kind:'food',amount:200,unit:'g',calories:150,protein:20,carbs:12,fat:3,source:'user'};
const b={id:'pudding-b',name:'Protein Pudding',kind:'food',amount:200,unit:'g',calories:190,protein:18,carbs:18,fat:5,source:'user'};
const added=[];
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
(async()=>{
 const dom=new JSDOM('<body data-nutrition-meal-type="Snack"><div class="nutrition-search-card"><input id="nutritionSearch"></div><div class="nutrition-results"></div></body>',{url:'https://example.test/',runScripts:'dangerously',pretendToBeVisual:true});
 const {window}=dom;
 window.CutCoachLibrary={exportData:()=>({items:[personalSkyr,personalCola,a,b]}),addCatalogItemToDay:(item,options)=>{added.push({item,options});return{id:'meal'}}};
 window.CutCoachFoodCatalog={items:()=>[],get:()=>null};window.CutCoachEverydayCatalog={items:()=>[],get:()=>null};window.render=()=>{};window.toast=()=>{};
 for(const source of [canonical,hardening]){const script=window.document.createElement('script');script.textContent=source;window.document.head.append(script)}
 window.CutCoachSearchConfidenceHardening151.attach(window.CutCoachIntelligentSearch128);
 const compatScript=window.document.createElement('script');compatScript.textContent=compatibility;window.document.head.append(compatScript);
 const api=window.CutCoachIntelligentSearch128;
 assert.equal(api.version,'1.5.1-alpha');
 const skyr=api.rowsFor('1 Skyr')[0];assert.equal(skyr.item.id,'personal-skyr');assert.equal(skyr.matchType,'ranked-personal');assert.equal(skyr.factor,1);
 const skyrGrams=api.rowsFor('250 g Skyr')[0];assert.equal(skyrGrams.item.id,'personal-skyr');assert.equal(skyrGrams.factor,.5);
 const cola=api.rowsFor('500 ml Cola')[0];assert.equal(cola.item.id,'personal-cola');assert.equal(cola.factor,1);
 const input=window.document.querySelector('#nutritionSearch');input.value='Haferflaken';input.dispatchEvent(new window.Event('input',{bubbles:true}));await wait(240);
 let host=window.document.querySelector('#nutritionMultiSearch');assert.ok(host.querySelector('article.review'));assert.equal(host.querySelector('[data-canonical-all]').disabled,true);
 input.value='Protein Pudding';input.dispatchEvent(new window.Event('input',{bubbles:true}));await wait(240);host=window.document.querySelector('#nutritionMultiSearch');
 const choices=host.querySelectorAll('[data-confidence-choice]');assert.equal(choices.length,2);choices[0].dispatchEvent(new window.MouseEvent('click',{bubbles:true}));assert.equal(added.length,0);assert.equal(host._canonicalRows[0].status,'matched');
 host.querySelector('[data-canonical-add]').dispatchEvent(new window.MouseEvent('click',{bubbles:true}));assert.equal(added.length,1);
 const resolved=window.CutCoachNutritionMultiSearch120.resolve('Skyr');assert.equal(resolved.match.id,'personal-skyr');assert.equal(window.CutCoachNutritionMultiSearch120.engineVersion(),'1.5.1-alpha');
 assert.match(manifest,/nutrition-search-confidence-hardening-v151\.js\?v=1\.5\.1-alpha/);assert.match(manifest,/1\.5\.1-compat/);
 dom.window.close();console.log('Confidence-Hardening 1.5.1: ok');
})().catch(error=>{console.error(error);process.exitCode=1});