'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const js=fs.readFileSync(path.join(root,'body-progress-v211.js'),'utf8');
assert.doesNotMatch(js,/bp-body-svg|Stilisierte Körpergrafik|function bodySvg/);
assert.match(js,/data:image\/webp;base64/);
assert.match(js,/anatomische CutCoach Körperdarstellung/i);
console.log('Body Progress 2.1.1: Keine alte SVG-Puppe oder Platzhalterfigur im sichtbaren Referenzneubau.');
