'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {JSDOM}=require('jsdom');
const root=path.resolve(__dirname,'..');
const read=name=>fs.readFileSync(path.join(root,name),'utf8');
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
(async()=>{
  const dom=new JSDOM(`<!doctype html><html><head></head><body><main class="app"><section class="screen active" data-screen="today"></section><section class="screen" data-screen="progress"><div class="bp211-shell" data-mode="body"></div></section></main><nav aria-label="Hauptnavigation" class="cc-glass-nav-v131 bp211-reference-nav"><button data-tab="today"></button><button data-tab="food"></button><button data-tab="progress"></button><button data-bp211-training-nav="1"></button><button data-tab="settings"></button></nav></body></html>`,{url:'https://example.test/cutcoach/#today',runScripts:'dangerously',pretendToBeVisual:true});
  const w=dom.window;w.scrollTo=()=>{};w.CutCoachGlassNavV131={enhance(){}};let selectedMode='body';w.CutCoachBodyProgress211={setMode(next){selectedMode=next;w.document.querySelector('.bp211-shell').dataset.mode=next}};
  const script=w.document.createElement('script');script.textContent=read('body-progress-v212-fix.js');w.document.head.append(script);if(w.document.readyState==='loading')w.document.dispatchEvent(new w.Event('DOMContentLoaded'));await wait(20);
  const nav=w.document.querySelector('nav');
  assert.equal(nav.querySelector('[data-bp211-training-nav]'),null,'Training darf außerhalb des Fortschritt-Screens nicht in der globalen Navigation bleiben.');
  assert.equal(nav.querySelectorAll(':scope > button').length,4,'Die Standardnavigation muss wieder exakt vier Einträge besitzen.');
  assert.match(nav.querySelector('[data-tab="food"]').innerHTML,/M12 5v14M5 12h14/,'Der zentrale Ernährungsbutton muss außerhalb des Fortschritts wieder das Plus zeigen.');
  w.document.querySelector('[data-screen="today"]').classList.remove('active');w.document.querySelector('[data-screen="progress"]').classList.add('active');await wait(20);
  assert.ok(nav.classList.contains('bp212-progress-nav'));
  assert.equal(nav.querySelectorAll(':scope > button').length,5,'Im Fortschritt dürfen genau fünf Tabs angezeigt werden.');
  assert.ok(nav.querySelector('[data-tab="progress"]').classList.contains('bp212-active'),'Im Körpermodus muss Fortschritt aktiv sein.');
  nav.querySelector('[data-bp211-training-nav]').click();await wait(20);
  assert.equal(selectedMode,'training');
  assert.ok(nav.querySelector('[data-bp211-training-nav]').classList.contains('bp212-active'),'Im Trainingsmodus muss Training aktiv sein.');
  assert.ok(!nav.querySelector('[data-tab="progress"]').classList.contains('bp212-active'),'Fortschritt darf im Trainingsmodus nicht gleichzeitig aktiv bleiben.');
  const css=read('body-progress-v212-fix.css'),loader=read('glass-nav-v131.js'),sw=read('sw.js'),pkg=JSON.parse(read('package.json'));
  assert.match(css,/safe-area-inset-top/);assert.match(css,/overflow-x:clip/);assert.match(css,/grid-template-columns:repeat\(4,minmax\(0,1fr\)\)/);assert.match(css,/grid-template-columns:repeat\(5,minmax\(0,1fr\)\)/);assert.match(css,/max-height:590px/);assert.match(css,/@media\(max-width:390px\)/);
  assert.match(loader,/body-progress-v212-fix\.css\?v=2\.1\.2-full-fix/);assert.match(loader,/body-progress-v212-fix\.js\?v=2\.1\.2-full-fix/);
  assert.match(sw,/body212-full-fix/);assert.match(sw,/body-progress-v212-fix\.css\?v=2\.1\.2-full-fix/);assert.match(pkg.scripts.test,/v212-body-progress-full-fix\.test\.js/);
  dom.window.close();console.log('Body Progress 2.1.2: Navigation, aktive Modi, Safe Area, Responsive Layout und Cachepfad geprüft.');
})().catch(error=>{console.error(error);process.exitCode=1});