'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const project=path.resolve(__dirname,'..');
const nutrition=fs.readFileSync(path.join(project,'nutrition-v73.js'),'utf8');
const version=fs.readFileSync(path.join(project,'version-v7.js'),'utf8');
const manifest=fs.readFileSync(path.join(project,'runtime-manifest.js'),'utf8');
const sw=fs.readFileSync(path.join(project,'sw.js'),'utf8');
const update=fs.readFileSync(path.join(project,'update.html'),'utf8');
assert.match(nutrition,/\$\('#nutritionEverydayQuick'\)\?\.remove\(\)/,'Alltagsbereich wird nicht entfernt');
assert.match(nutrition,/\$\('#journalCoachText'\)\?\.remove\(\)/,'Impuls-Infotext wird nicht entfernt');
assert.doesNotMatch(nutrition,/quick\.innerHTML=/,'Alltags-Chips werden weiterhin erzeugt');
assert.match(version,/const RELEASE='7\.3\.1'/,'Releaseversion ist nicht 7.3.1');
assert.match(manifest,/version:'7\.3\.1'/,'Cacheversion ist nicht 7.3.1');
assert.match(manifest,/nutrition-v73\.js\?v=7\.3\.1/,'Bereinigtes Ernährungsmodul fehlt im Cache');
assert.match(sw,/runtime-manifest\.js\?v=7\.3\.1/,'Service Worker lädt falsches Manifest');
assert.match(update,/sw\.js\?v=7\.3\.1-force/,'Update-Seite installiert nicht 7.3.1');
console.log('CutCoach 7.3.1 UI cleanup test: ok');
