'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const project=path.resolve(__dirname,'..');
const nutrition=fs.readFileSync(path.join(project,'nutrition-v73.js'),'utf8');
const version=fs.readFileSync(path.join(project,'version-v7.js'),'utf8');
const manifest=fs.readFileSync(path.join(project,'runtime-manifest.js'),'utf8');
const sw=fs.readFileSync(path.join(project,'sw.js'),'utf8');
const update=fs.readFileSync(path.join(project,'update.html'),'utf8');
const cleanupCss=fs.readFileSync(path.join(project,'ui-cleanup-v732.css'),'utf8');
const journalLive=fs.readFileSync(path.join(project,'journal-live-nav-v127.js'),'utf8');
assert.match(nutrition,/nutritionEverydayQuick/,'Alltagsbereich wird nicht entfernt');
assert.ok(nutrition.includes('coachText.hidden=true'),'Impuls-Infotext wird nicht ausgeblendet');
assert.ok(nutrition.includes("coachText.style.display='none'"),'Impuls-Infotext bleibt im Layout sichtbar');
assert.equal(nutrition.includes('quick.innerHTML='),false,'Alltags-Chips werden weiterhin erzeugt');
assert.match(nutrition,/observer\.observe\(root/,'Nutrition-Beobachtung ist nicht auf den Food-Screen begrenzt');
assert.doesNotMatch(nutrition,/observe\(document\.documentElement/,'Nutrition-Modul beobachtet weiterhin die gesamte App');
assert.ok(cleanupCss.includes('#journalCheckInsight'),'Tagescheck-Info wird nicht verborgen');
assert.ok(cleanupCss.includes('.journal-macros article > em'),'Makro-Prozentwerte werden nicht verborgen');
assert.ok(cleanupCss.includes('.macro-v7-gap'),'Makro-Restwerte werden nicht verborgen');
assert.ok(cleanupCss.includes('white-space:nowrap'),'Kohlenhydrate wird nicht einzeilig gehalten');
assert.ok(cleanupCss.includes('letter-spacing:-.035em'),'Kohlenhydrate wurde nicht kompakt angepasst');
assert.match(journalLive,/CutCoachJournalV72\?\.render/,'Live-Journal wird nach Datenänderungen nicht neu berechnet');
assert.match(journalLive,/Schnell anlegen/,'Manueller Eintrag wurde nicht verständlicher benannt');
assert.match(journalLive,/Noch nicht eingetragen/,'Doppelte Schritte-Anzeige wird nicht korrigiert');
assert.ok(version.includes("const RELEASE='2.3.0 Alpha'"),'Releaseversion ist nicht 2.3.0 Alpha');
assert.ok(manifest.includes("version:'2.3.0-alpha'"),'Cacheversion ist nicht 2.3.0 Alpha');
assert.ok(manifest.includes('journal-live-nav-v127.js?v=1.3.2-alpha'),'Repariertes Live-Journal-Modul fehlt im Cache');
assert.ok(manifest.includes('nutrition-v73.js?v=7.3.2'),'Nutrition-QA-Modul fehlt im Cache');
assert.ok(manifest.includes('ui-cleanup-v732.css?v=7.3.3'),'Cleanup-CSS fehlt im Cache');
assert.ok(manifest.includes('nutrition-search-exact-whole-v170.js?v=1.9.6-alpha'),'Artikel- und Sequenzschutz fehlt im Cache');
assert.ok(sw.includes('runtime-manifest.js?v=2.3.0-alpha'),'Service Worker lädt falsches Manifest');
assert.ok(sw.includes('search196-article-sequence'),'Service Worker enthält die Artikel- und Sequenzgeneration nicht');
assert.ok(update.includes('sw.js?v=2.3.0-alpha'),'Update-Seite installiert nicht 2.3.0 Alpha');
console.log('CutCoach 2.3.0 Alpha UI and fixed live journal patch: ok');
