'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const project=path.resolve(__dirname,'..');
const js=fs.readFileSync(path.join(project,'journal-smart-v740.js'),'utf8');
const css=fs.readFileSync(path.join(project,'journal-smart-v740.css'),'utf8');
const manifest=fs.readFileSync(path.join(project,'runtime-manifest.js'),'utf8');
const sw=fs.readFileSync(path.join(project,'sw.js'),'utf8');
const version=fs.readFileSync(path.join(project,'version-v7.js'),'utf8');
const update=fs.readFileSync(path.join(project,'update.html'),'utf8');
assert.match(js,/coach-v74-collapsed/,'Coach kann nicht eingeklappt werden');
assert.match(js,/preferredMeal/,'Tageszeitabhängige Mahlzeitenlogik fehlt');
assert.match(js,/nutritionSearch/,'Direkte Coach-Suche fehlt');
assert.match(js,/requestAnimationFrame/,'Render-Aktualisierungen werden nicht zusammengefasst');
assert.match(js,/rootObserver\.observe\(root/,'DOM-Beobachtung ist nicht auf das Tagebuch begrenzt');
assert.doesNotMatch(js,/observe\(document\.documentElement/,'Teure globale Dauerbeobachtung ist weiterhin aktiv');
assert.doesNotMatch(js,/setInterval/,'Die Tageszeitprüfung läuft weiterhin dauerhaft im Hintergrund');
assert.match(js,/document\.hidden[\s\S]*scheduleMealRefresh/,'Zeitabhängige Aktualisierung pausiert bei unsichtbarer App nicht');
assert.match(css,/journal-energy-card/,'Kompakter Tagesüberblick fehlt');
assert.match(css,/meal-v74-current/,'Aktuelle Mahlzeit wird nicht hervorgehoben');
assert.match(css,/focus-visible/,'Tastaturfokus für Coach-Schalter fehlt');
assert.match(manifest,/version:'2\.3\.0-alpha'/,'Manifestversion ist falsch');
assert.match(manifest,/journal-smart-v740\.js\?v=1\.0\.1-alpha/,'Stabilisiertes Journal fehlt im Cache');
assert.match(sw,/runtime-manifest\.js\?v=2\.3\.0-alpha/,'Service Worker lädt falsches Manifest');
assert.match(version,/const RELEASE='2\.3\.0 Alpha'/,'Releaseversion ist falsch');
assert.match(update,/sw\.js\?v=2\.3\.0-alpha/,'Update-Seite installiert nicht 2.3.0 Alpha');
console.log('CutCoach 2.3.0 Alpha journal stabilization test: ok');
