'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const project=path.resolve(__dirname,'..');
const packageJson=JSON.parse(fs.readFileSync(path.join(project,'package.json'),'utf8'));
const human=packageJson.version.replace(/-alpha$/,' Alpha');
const js=fs.readFileSync(path.join(project,'journal-smart-v740.js'),'utf8');
const css=fs.readFileSync(path.join(project,'journal-smart-v740.css'),'utf8');
const manifest=fs.readFileSync(path.join(project,'runtime-manifest.js'),'utf8');
const sw=fs.readFileSync(path.join(project,'sw.js'),'utf8');
const version=fs.readFileSync(path.join(project,'version-v7.js'),'utf8');
const update=fs.readFileSync(path.join(project,'update.html'),'utf8');
assert.match(js,/coach-v74-collapsed/,'Coach kann nicht eingeklappt werden');
assert.match(js,/preferredMeal/,'Tageszeitabhängige Mahlzeitenlogik fehlt');
assert.match(js,/nutritionSearch/,'Direkte Coach-Suche fehlt');
assert.match(js,/requestAnimationFrame/,'Render-Aktualisierungen werden nicht zusammengefasst');
assert.match(js,/rootObserver\.observe\(root/,'DOM-Beobachtung ist nicht auf das Tagebuch begrenzt');
assert.doesNotMatch(js,/observe\(document\.documentElement/,'Teure globale Dauerbeobachtung ist weiterhin aktiv');
assert.match(js,/journal-live-nav-v127\.js\?v=1\.3\.3-alpha/,'Smart-Journal lädt nicht den gehärteten Live-Refresh.');
assert.match(css,/journal-energy-card/,'Kompakter Tagesüberblick fehlt');
assert.match(css,/meal-v74-current/,'Aktuelle Mahlzeit wird nicht hervorgehoben');
assert.match(css,/focus-visible/,'Tastaturfokus für Coach-Schalter fehlt');
assert.ok(manifest.includes(`version:'${packageJson.version}'`),'Manifestversion stimmt nicht mit package.json überein.');
assert.match(manifest,/journal-smart-v740\.js\?v=1\.0\.1-alpha/,'Stabilisiertes Journal fehlt im Cache');
assert.ok(sw.includes(`runtime-manifest.js?v=${packageJson.version}`),'Service Worker lädt falsches Manifest.');
assert.ok(version.includes(`const RELEASE='${human}'`),'Releaseversion stimmt nicht mit package.json überein.');
assert.ok(version.indexOf('loadJournalLive127();')<version.indexOf("addScript('journal-smart-v740'"),'Live-Refresh muss vor dem Smart-Journal angefordert werden.');
assert.match(update,/const SERVICE_WORKER_URL='\.\/sw\.js'/,'Update-Seite verwendet nicht den kanonischen Service Worker.');
console.log(`CutCoach ${human} Smart-Journal-Test: ok`);